### PR TITLE
use more if TYPE_CHECKING

### PR DESCRIPTION
**Pull request by etam**

### CODE REVIEW

**Comment by Wiezzel** [comment]
Is this work-in-progress or ready for review?

**Comment by etam** [comment]
it's an almost ready work-in-progress. Unfortunately using GitHubs WIP disables running tests on buildbot. But I think it should pass this time.

**Comment by etam** [comment]
it's ready

**Comment by Wiezzel** [comment]
What exactly is the benefit of doing this? Does importing stuff like `GetConfigFn`, `EnvId` or `EnvironmentManager` impair the performance?

**Comment by etam** [comment]
It should improve performance of starting the application, by avoiding unneeded imports.

**Review by Wiezzel — APPROVED** [review]
OK

**Pull request merged**
