### PR TITLE
Merge b0.11.0 to develop

### PR DESCRIPTION
**Pull request by jiivan**

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM!

What is the difference between `b0.11.0` and `b.0.11.0_to_develop`?

**Comment by jiivan** [comment]
@maaktweluit this branch has `develop` merged to itself, conflicts solved, and lints removed.

**Comment by maaktweluit** [comment]
Thanks, clear to me.

@mfranciszkiewicz Is this the way we can handle releases without duplicates?

**Comment by mfranciszkiewicz** [comment]
@maaktweluit Yes, these changes haven't been merged to `develop`.

**Review by mfranciszkiewicz — APPROVED** [review]

**Pull request merged**
