### PR TITLE
Only allow one offer per provider_id per task in queue

### PR DESCRIPTION
**Pull request by maaktweluit**
this issue occurs when 2 tasks are requested in a 2 node setup.

```
INFO     [golem.marketplace.brass_marketplace] Ordering providers for task: dbe198b0-20bc-11ea-b92a-43ed6a67ef11
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s). "task_id='dbe198b0-20bc-11ea-b92a-43ed6a67ef11', node='e57a9382..708bc0dc'"
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s). "task_id='dbe198b0-20bc-11ea-b92a-43ed6a67ef11', node='e57a9382..708bc0dc'"
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s). "task_id='dbe198b0-20bc-11ea-b92a-43ed6a67ef11', node='e57a9382..708bc0dc'"
```

### CODE REVIEW

**Review by prekucki — APPROVED** [review]
Hmm. Logs look more clear, but... after this change requestor assigns subtasks sequentially one-by-one. without any concurrency. 

## Test:

### Test env:

* requestor name=g1, node_id=cb4bfd6eade9b7f8...ce72ce0ee6e7dc62   
* provider name=g2, node_id=500ff37fb7309721...6e0d26789eca5354
* provider name=g3, node_id=043aba296afc93b4...aee96ea82ed2f563 
* provider name=g4, node_id=bf6915ba66352c8b...19720b68feaa39d6
* provider name=g5, name_id=430dcd8f28afc17d...cb6946a789616a91
* provider name=g6, name_id=acb670d788230659...8be9fe62fdbb8228

### Blender task test

golemcli tasks create test.json

```json
{
"type": "Blender",
"compute_on": "cpu",
"name": "smok",
"timeout": "0:10:05",
"subtask_timeout": "0:09:50",
"subtasks_count": 10,
"bid": 0.1,
"resources": [
        "/home/prekucki/projects/golem-tests/test_task_1/puchacz_canopy.jpg",
        "/home/prekucki/projects/golem-tests/test_task_1/wlochaty3.blend"
],
"options": {
            "output_path": "/home/prekucki/projects/golem-tests/out",
            "format": "PNG",
                "frame_count": 0,
                "frames": "1",
                "compositing": false,
            "resolution": [
                320,
                240
            ]
        }
 }
```

on branch mwu/b0.22/single-offer

```tasks subtasks list bda91d90-203b-11ea-8441-cb4bfd6eade9
┌────────┬────────────────────────────────────────┬────────────┬────────────┐
│  node  │  subtask id                            │  status    │  progress  │
├────────┼────────────────────────────────────────┼────────────┼────────────┤
│  g6    │  cd07ecd0-203b-11ea-9d2d-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  eefc6ad8-203b-11ea-9514-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  076fd3d4-203c-11ea-b365-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  240d3c94-203c-11ea-bf5e-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  3f7738f4-203c-11ea-8a56-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  5c11bcb0-203c-11ea-b296-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  78154f3a-203c-11ea-9168-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  91bb53a6-203c-11ea-99ad-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  ae512a66-203c-11ea-9dd1-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  c92405c2-203c-11ea-926c-cb4bfd6eade9  │  Finished  │  100.0 %   │
└────────┴────────────────────────────────────────┴────────────┴────────────┘
```

on b0.22 result is:

```
tasks subtasks list 7df80e5a-203d-11ea-83c7-cb4bfd6eade9
┌────────┬────────────────────────────────────────┬────────────┬────────────┐
│  node  │  subtask id                            │  status    │  progress  │
├────────┼────────────────────────────────────────┼────────────┼────────────┤
│  g6    │  8a4437b4-203d-11ea-bcbc-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g4    │  8a490a48-203d-11ea-82c5-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g3    │  8a4c9858-203d-11ea-b308-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g2    │  8a514580-203d-11ea-9755-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g5    │  8a572524-203d-11ea-a9da-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g3    │  acd9be6e-203d-11ea-ab1b-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g6    │  b5d2e4a6-203d-11ea-9f30-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g2    │  c382d0c2-203d-11ea-9bbf-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g5    │  c3897380-203d-11ea-b026-cb4bfd6eade9  │  Finished  │  100.0 %   │
│  g4    │  dbf9c13e-203d-11ea-bb1c-cb4bfd6eade9  │  Finished  │  100.0 %   │
└────────┴────────────────────────────────────────┴────────────┴────────────┘
```

**Review by prekucki — CHANGES_REQUESTED** [review]
bug. described in prev comment.

**Comment by maaktweluit** [comment]
@prekucki thanks for the input! 

For me in a test between 2 nodes the provider got 2 subtasks assigned at the same time.
Based on your input it seems this is a bug in the marketplace, not in the loop.

Will try a new fix!

**Comment by maaktweluit** [comment]
@prekucki @mfranciszkiewicz @shadeofblue made a alternative solve. please check again, will fix tests if this solve is working for all of us :)

**Review by tworec — APPROVED** [review]
lgtm

**Review by jiivan — APPROVED** [review]

**Review by mbenke — CHANGES_REQUESTED** [review]
It seems now one provider cannot compute more than one subtask of a given task. So if you run a WASM task with multiple subtasks (and VbR) on 2 provider, it gets stuck after first subtask.

**Comment by maaktweluit** [comment]
> It seems now one provider cannot compute more than one subtask of a given task. So if you run a WASM task with multiple subtasks (and VbR) on 2 provider, it gets stuck after first subtask.

Investigated this in a chat with @mbenke and it looks like another bug is causing this behaviour. The same issue is on `b0.22` currently. We will run the same test after b0.22 is patched and then branch is updated.

**Review by mbenke — APPROVED** [review]

**Pull request closed without merging**
