### PR TITLE
Fix resource package subdirectories

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
Resolves: #3851

### CODE REVIEW

**Review by magdasta — APPROVED** [review]

**Review by kmazurek — APPROVED** [review]
LGTM, should resolve #3851

**Comment by mplebanski** [comment]
It looks to me like a blender specific patch in generic code

**Comment by mfranciszkiewicz** [comment]
@mplebanski How is it blender specific?

**Comment by mfranciszkiewicz** [comment]
The flattened directory structure change was never supposed to be implemented. *That* approach was use-case specific. This preserves the original directory structure and is the expected behaviour.

**Comment by mplebanski** [comment]
As discussed offline, OK to merge for me.

**Pull request merged**
