### PR TITLE
update coincurve

### PR DESCRIPTION
**Pull request by ofek**
https://github.com/ofek/coincurve#700

### CODE REVIEW

**Comment by ofek** [comment]
@mfranciszkiewicz @etam Can this be merged?

**Comment by etam** [comment]
This dependency should be removed from this repository. It's only referenced at https://github.com/golemfactory/golem-messages

**Comment by ofek** [comment]
@etam https://github.com/golemfactory/golem-messages/pull/129

**Comment by etam** [comment]
#2058

**Pull request closed without merging**
