### PR TITLE
Fix order of help entries in golemcli

### LINKED ISSUE #3021: correct order of arguments
After `golemcli network` additional arguments are printed before the primary list

### PR DESCRIPTION
**Pull request by dybi**
resolves: https://github.com/golemfactory/golem/issues/3021

### CODE REVIEW

**Comment by etam** [comment]
This touches private parts of standard library. This smells bad. Isn't it possible to add those things to argument parser in correct order?

**Comment by dybi** [comment]
@etam, quite frankly, I wasn't able to figure out how to do it **without** touching the internals. The thing is, that options for parent parser (`self.shared_parser`) are normally added first. Even though, I tried to tinker with internals as carefully as possible ;)

**Review by shadeofblue — APPROVED** [review]
strawberry leaf

**Comment by etam** [comment]
@dybi you can trigger rebuilds directly from buildbot web interface

**Pull request merged**
