### PR TITLE
Remove nopayments flag

### PR DESCRIPTION
**Pull request by Krigpl**
There are no plans to use it.

### CODE REVIEW

**Comment by mfranciszkiewicz** [comment]
You should also remove the `transaction_system` param in `tests/golem/tasks/dummy/runner.py`

**Comment by Krigpl** [comment]
@mfranciszkiewicz Yeah, just did :)

**Comment by Krigpl** [comment]
Ping

**Comment by etam** [comment]
`if [...].transaction_system` still exists in:
- `TaskServer.send_result`
- `TaskServer.accept_result`
- `TaskServer.__connection_for_task_result_established`

-----

Tests failed, because `TaskServer.__connection_for_task_result_established` calls `get_payment_address()` on a mock object, which returns a mock object, which then cbor fails to serialize.

**Review by etam — CHANGES_REQUESTED** [review]
`if [...].transaction_system` still exists in:
- `TaskServer.send_result`
- `TaskServer.accept_result`
- `TaskServer.__connection_for_task_result_established`

-----

Tests failed, because `TaskServer.__connection_for_task_result_established` calls `get_payment_address()` on a mock object, which returns a mock object, which then cbor fails to serialize.

**Review by etam — APPROVED** [review]

**Pull request merged**
