### PR TITLE
b0.22 - task-api - disable providing while requesting without config

### PR DESCRIPTION
**Pull request by maaktweluit**
replace `accept_tasks` config toggle with `requested_task_manager.has_unfinished_tasks()`

### CODE REVIEW

**Review by mfranciszkiewicz — CHANGES_REQUESTED** [review]
There is a race condition within this solution - the node may request a subtask while a task is being created. Subtasks are requested frequently enough for this issue to be apparent. The config change was a faster state trigger (side effects aside).

What I'd suggest is to return early from `Client.change_config` for chosen config properties (e.g. whitelisted by the config approver) or create a separate method that only does `self.config = self.config_approver.change_config(new_config_desc)` for those properties.

**Comment by maaktweluit** [comment]
@mfranciszkiewicz i do not see a race created here, now tasks are no longer picked up from `requested_task_manager.create_task` that happens a few lines before the config was turned off.

**Comment by mfranciszkiewicz** [comment]
@maaktweluit It simply takes longer from calling `comp.task.create` to creating a model in the database (so that `has_unfinished_tasks()` returns True) than changing an option in config (and relying on that value in code).
 In the meantime, the Golem node may request a subtask from the network and if that succeeds, the computation flow will continue in parallel with requesting a task.

**Comment by mfranciszkiewicz** [comment]
Alternative solution merged #4976

**Pull request closed without merging**
