### PR TITLE
Remove resource session

### PR DESCRIPTION
**Pull request by Elfoniok**

### CODE REVIEW

**Comment by etam** [comment]
Deleting code looks nice!

But why are there submodules?

**Comment by mfranciszkiewicz** [comment]
Are you planning on removing `FilesProtocol`, `FileProducer`s and `FileConsumer`s?

**Comment by Elfoniok** [comment]
I dont know why? This is a result of analyzing golem p2p messages in terms of amount of messages on sec for p2p session. I have discovered that ResourceSession is not used anymore and is obfuscating code base.

**Comment by Elfoniok** [comment]
Submodules added by mistake are gone now.

**Review by mfranciszkiewicz — APPROVED** [review]

**Review by etam — APPROVED** [review]

**Pull request merged**
