### PR TITLE
Environment attribute added into "provider_state"

### PR DESCRIPTION
**Pull request by mdtanrikulu**
Should be merged at the together with golemfactory/golem-electron#457

### CODE REVIEW

**Review by Krigpl — APPROVED** [review]
lgtm I think

**Review by etam — APPROVED** [review]
ok

**Comment by etam** [comment]
Is this supposed to go to b0.18.0 branch?

**Comment by mdtanrikulu** [comment]
> Is this supposed to go to b0.18.0 branch?

Yep.

**Pull request merged**
