### PR TITLE
Hide console during installation

### PR DESCRIPTION
**Pull request by maaktweluit**
Hide the console windows while configuring hyperv / docker for windows

### CODE REVIEW

**Comment by Wiezzel** [comment]
@maaktweluit There is one thing you should double-check: If the SMB share is not created and you start Golem does it prompt to create it?

**Comment by maaktweluit** [comment]
@Wiezzel tested this and it seems the share is not created at all on boot.

Golem only calls `apply_config` from node.py, while `update_config` (called later from client.py and friends) creates the share.

Think you found a new bug, should i try to fix it in this PR or make a new issue?

**Comment by Wiezzel** [comment]
@maaktweluit 
> Think you found a new bug, should i try to fix it in this PR or make a new issue?

It's up to you. But the fix must be applied before merging this PR. My concern is that even when the script is run on Golem boot the `-WindowStyle hidden` option might cause the prompt not to appear.

**Comment by maaktweluit** [comment]
@Wiezzel after some more tests the `-WindowStyle` does not affect the prompt, it still appeared even if the console is hidden

**Review by mfranciszkiewicz — APPROVED** [review]

**Review by Wiezzel — APPROVED** [review]

**Pull request merged**
