### PR TITLE
DO NOT MERGE Common crypto package - RSA keys, DH params, X509 certs

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
**DO NOT MERGE** This PR will be rebased onto develop when b0.22 is merged.

A prerequisite branch for introducing gRPC SSL support.

New module for:
- RSA key generation and (de)serialization
- DH params generation and (de)serialization
- X509 cert generation and (de)serialization

### CODE REVIEW

**Review by maaktweluit — CHANGES_REQUESTED** [review]
LGTM! Nice cleanup :)

Maybe add some tests for the new file `golem/crypto.py`?

**Review by Wiezzel — APPROVED** [review]
Nice cleanup.
Agreed with @maaktweluit that some unit tests would be nice.

**Comment by mfranciszkiewicz** [comment]
These are basically wrappers for the provided crypto functions. New unit tests would only check whether those functions were called with the provided parameters and IMO that's not worth the effort. It makes little sense to (re)test `cryptography`.

The `CertificateManager` test uses these functions under the hood and provides a better test case. The E2E test validates whether the generated key, DH params and the certificate are generated properly and conform to general requirements (e.g. running with `Crossbar`).

**Comment by maaktweluit** [comment]
Sounds good to me, maybe add them to the coverage exclusion list with a small comment like above

**Review by maaktweluit — APPROVED** [review]

**Pull request closed without merging**
