### PR TITLE
node_integration_tests - Remove repeated part of datadirs

### PR DESCRIPTION
**Pull request by maaktweluit**
```
old: scripts.node_integration_tests.tests.test_golem.GolemNodeTest.test_frame_restart
new:                                      test_golem.GolemNodeTest.test_frame_restart
```

### CODE REVIEW

**Review by Wiezzel — APPROVED** [review]
Looks ok. Do you still need to replace `__name__` though?

**Review by shadeofblue — APPROVED** [review]

**Comment by maaktweluit** [comment]
Was looking at that `__name__` and it indeed seems not required.

@shadeofblue @etam do you know why it is there? can we safely remove it?

**Comment by mfranciszkiewicz** [comment]
AFAICT replacing `__name__` was supposed to have a similar result, `GolemNodeTest.test_frame_restart` in this example.

**Review by mfranciszkiewicz — COMMENTED** [review]
I think it would be nicer to dynamically resolve the required path or build the relative id from the scratch. Some helpful definitions from the `unittest` module:

```
def id(self):
    return "%s.%s" % (strclass(self.__class__), self._testMethodName)
```

```
def strclass(cls):
    return "%s.%s" % (cls.__module__, cls.__qualname__)
```

**Comment by maaktweluit** [comment]
@Wiezzel @mfranciszkiewicz Based on the review comments i updated the PR to use `__name__` again for the replacement, so the test dir always starts with the file/module name.

**Review by mfranciszkiewicz — APPROVED** [review]

**Pull request merged**
