### PR TITLE
Gr293 fix expect income

### PR DESCRIPTION
**Pull request by shadeofblue**
closes GR293

### CODE REVIEW

**Comment by ederenn** [comment]
checked on requesting on Linux and Windows, on those systems seems like proper amount of money is sent, both in logs and in GUI

Linux:
```INFO     [golem.ethereum.paymentprocessor    ] Adding payment for da613f82-f677-11e9-8b07-2f67ff27ad1e to 0xe1D92383296F093515643ff8Fc5Cd128Fc038559 (0.01666667 GNTB)
INFO     [golem.ethereum.paymentprocessor    ] Reserved 0.133 GNTB
INFO     [golem.ethereum.fundslocker         ] Removing subtask lock for task '86054cf8-f677-11e9-a07d-2f67ff27ad1e'
INFO     [golem.ethereum.transactionsystem   ] Unlocking 0.017 GNTB for 1 payments
INFO     [golem.task.taskmanager             ] Task finished! task_id='86054cf8-f677-11e9-a07d-2f67ff27ad1e'
```

```
>> tasks dump 86054cf8-f677-11e9-a07d-2f67ff27ad1e
{
  "id": "86054cf8-f677-11e9-a07d-2f67ff27ad1e",
  "status": "Finished",
  "time_remaining": 0.0,
  "subtasks_count": 4,
  "progress": 1.0,
  "cost": null,
  "fee": null,
  "estimated_cost": "66666666666666668",
  "estimated_fee": "448000000000000",
  "last_updated": 1571933135.128212,
  "time_started": 1571932882.270821,
  "concent_enabled": false,
  "resources": [
    "/home/ederenn/Desktop/Host_Share_Folder/test files/small_shark100.blend"
  ],
  "name": "small_shark1002",
  "options": {
    "frame_count": 2,
    "output_path": "/home/ederenn/Documents/small_shark1002_2019-10-24_18-01-22",
    "format": "PNG",
    "resolution": [
      400,
      400
    ],
    "frames": "1-2",
    "compositing": false,
    "samples": 1000
  },
  "preview": "/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/86054cf8-f677-11e9-a07d-2f67ff27ad1e/tmp/current_task_preview1.PNG",
  "subtask_timeout": "0:10:00",
  "type": "Blender",
  "timeout": "0:10:00",
  "bid": 0.1,
  "compute_on": "cpu",
  "status_
```

**Review by mbenke — APPROVED** [review]

**Comment by ederenn** [comment]
for several runs info  `Batch transfer amount does not match`dos not repeat but Golem seems to have problems with detecting batch events. Both sides for providers and partially for requestor. Not after every requestor restart there was batching for finished computations. On providers some of today's incomes are confirmed, some others which were computed earlier are still in awaiting state.

there were 3 nodes connected, 1 linux, 2 windows, all of them were requesting and providing
[golem_linux.log](https://github.com/golemfactory/golem/files/3772630/golem_linux.log)
[golem_win1.log](https://github.com/golemfactory/golem/files/3772632/golem_win1.log)
[golem_win_2.log](https://github.com/golemfactory/golem/files/3772633/golem_win_2.log)

**Comment by ederenn** [comment]
I got `batch transfer does not match` on branch b0.22 twice, one time batch was matching


```
2019-11-15 12:32:53 INFO     golemapp                            GOLEM Version: 0.21.0+dev406.g6c362ef
2019-11-15 12:32:53 INFO     golemapp                            Protocol Version: 32
2019-11-15 12:32:53 INFO     golemapp                            golem_messages Version: 3.14.0

```
```
2019-11-15 12:33:13 INFO     golem_sci.implementation            Detected event <BatchTransferEvent tx: 0xa31d0302b5f177551f8d146852265381d2b826f765e183fd48b23d1114b76cc7 sender: 0x2C9287402aA1797e6c32cAC433130cB63C72ac2F receiver: 0x10d4425e30C45c7409f712B0c4F85Dce2272cfAB amount: 0.02604203369830482 closure_time: 1573749343>
2019-11-15 12:33:13 WARNING  golem.ethereum.incomeskeeper        Batch transfer amount does not match, expected 0.025883593183531135, got 0.02604203369830482

```

```
2019-11-15 15:39:22 INFO     golem_sci.implementation            Detected event <BatchTransferEvent tx: 0x81c49a392b80322b5adb9bc130849adbe76600537076cc4a78aef1019e1cf23f sender: 0xe1D92383296F093515643ff8Fc5Cd128Fc038559 receiver: 0x10d4425e30C45c7409f712B0c4F85Dce2272cfAB amount: 0.017172219989606385 closure_time: 1573826625>
2019-11-15 15:39:22 WARNING  golem.ethereum.incomeskeeper        Batch transfer amount does not match, expected 0.017138903263000833, got 0.017172219989606385

```

one matching:
```
2019-11-15 13:49:55 INFO     golem_sci.implementation            Detected event <BatchTransferEvent tx: 0x8208debbe9e654a1ac1062cdf79d57fe925dcc1a2ac0e9d77208315f7a1fefe1 sender: 0xe1D92383296F093515643ff8Fc5Cd128Fc038559 receiver: 0x10d4425e30C45c7409f712B0c4F85Dce2272cfAB amount: 0.04166666666666667 closure_time: 1573821819>
```

**Comment by mbenke** [comment]
Shouldn't this be merged into b0.22?

**Comment by shadeofblue** [comment]
> Shouldn't this be merged into b0.22?

it is https://github.com/golemfactory/golem/commits/b0.22?after=c77ff35c72cf739db927139ec6f4be6e7d48ca51+104

**Comment by ederenn** [comment]
so, why I got this error on b.022 branch?

**Comment by mbenke** [comment]
@ederenn it seems unrelated to usage market. I have now proposed #4912 to make it easier to track payments in logs.

**Pull request merged**
