### PR TITLE
Finished part 2 of installer Docker for Windows

### PR DESCRIPTION
**Pull request by maaktweluit**
- Create `golem-docker` user
- Create the default datadir
- Run `create-share.ps1`.
  - for mainnet: `C:\Users\NAME\AppData\Local\golem\default\mainnet\ComputerRes` 
  - for testnet: `C:\Users\NAME\AppData\Local\golem\default\rinkeby\ComputerRes`
- Expand disabled windows versions ( part 1: review comment )

Powershell screenshots:
screen shot 2018-08-30 at 15 23 47
screen shot 2018-08-30 at 15 21 23
screen shot 2018-08-30 at 15 22 20
screen shot 2018-08-30 at 15 22 36

### CODE REVIEW

**Review by Wiezzel — CHANGES_REQUESTED** [review]
User without password won't do. Please set a password (preferably the same as user name):
```
$securePassword = ConvertTo-SecureString $golemUserName -AsPlainText -Force
New-LocalUser -Name $golemUserName -Password $securePassword
```

**Comment by maaktweluit** [comment]
@Wiezzel Added the line as requested :)

**Review by Wiezzel — APPROVED** [review]

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by maaktweluit** [comment]
Thanks for the approvals!

updated target branch to develop, then this PR, will test 1 more time before merging

**Comment by maaktweluit** [comment]
Tests succeeded! @mfranciszkiewicz @Wiezzel please check the last commit again

**Comment by Wiezzel** [comment]
Tested again. Worked fine. 👍

**Pull request merged**
