### PR TITLE
Don't allow use to chose Docker Toolbox if Hyper-V is installed

### LINKED ISSUE #4060: Golem with Docker Toolbox is not starting, upgrade from 19.0 with hyperv to 19.1 with toolbox
## Description

**Golem Version**: 0.19.1

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): 0.1.19

**OS** [e.g. Windows 10 Pro]: Windows 10

**Branch** (if launched from source): - 

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

Golem with Docker Toolbox is not starting. After upgrade from 19.0 with hyperv to 19.1 with toolbox

**Actual result**:

Golem app is hanging after typing in password 

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
System with Golem 0.19.0 is needed.

1. Install 0.19.1 Golem Version without Hyperv
2. Check in Windows Features if Hyperv is disabled
3. Install Docker Toolbox 18.6 version
https://github.com/docker/toolbox/releases/download/v18.06.1-ce/DockerToolbox-18.06.1-ce.exe
4. In Powershell with administrative rights type in 

```
C:\windows\System32\InfDefaultInstall.exe "C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.inf"
Set-ItemProperty HKLM:\system\currentcontrolset\services\vboxdrv -Name ImagePath -Value "\??\C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv\VBoxDrv.sys"
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\VBoxDrv" -Name "DelayedAutostart" -Value 1 -Type DWORD
Start-Service vboxdrv
```

5. Restart system
6. Run Docker Toolbox Quickstart, wait for Docker to launch
7. Run Golemapp
8. Golem will hang after typing in password on "Logged in"

## Expected behavior
Golem should launch and connect to nodes

## Logs and any additional context

[golem.log](https://github.com/golemfactory/golem/files/3024430/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

### PR DESCRIPTION
**Pull request by Wiezzel**
The installer doesn't support downgrading from Hyper-V to Docker Toolbox. Therefore user should not be presented the dialog window prompting to select the preferred hypervisor if Hyper-V is already installed.

Resolves #4060

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]

**Comment by ederenn** [comment]
not able to test it properly, binaries build on b0.20 branch are not working
https://github.com/golemfactory/golem/issues/4271

**Comment by ederenn** [comment]
1. upgrade hvperv->hyperv,  no pop-up (supporting hyperv),  all hyperv boxes checked in windows features, golem connect to nodes,


2. upgrade toolbox -> hyperv, pop-up (supporting hyperv) available, all hyperv boxes checked in windows features, , golem connect to nodes, new  terms of use to be accepted


3. installation on clean state with no hyperv, pop-up (supporting hyperv) available, all hyperv boxes checked in windows features, , golem connect to nodes


4. installation on clean state with hyperv preinstalled, no pop-up (supporting hyperv),hyperv boxes checked in windows features, golem is not launching

```
C:\Users\ederenn>docker-machine ls
'docker-machine' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ederenn>
```
 
 ```
2019-06-04 18:36:34 WARNING  golem.docker.hypervisor.docker_machine DockerMachine: failed to list VMs: CalledProcessError(127, '[WinError 2] The system cannot find the file specified')
2019-06-04 18:36:36 ERROR    golem.docker.manager                
                ***************************************************************
                No supported VM hypervisor was found.
                Golem will not be able to compute anything.
                hypervisor.setup() returned RuntimeError("Command '['powershell.exe', '-NoProfile', '-ExecutionPolicy', 'RemoteSigned', '-File', 'C:\\\\Users\\\\ederenn\\\\AppData\\\\Local\\\\Temp\\\\_MEI57562\\\\scripts\\\\docker\\\\get-default-vswitch.ps1']' returned non-zero exit status 1.\nstdout: \nstderr: Get-VMSwitch : You do not have the required permission to complete this task. Contact the administrator of the \r\nauthorization policy for the computer 'DESKTOP-90IS6JB'.\r\nAt C:\\Users\\ederenn\\AppData\\Local\\Temp\\_MEI57562\\scripts\\docker\\get-default-vswitch.ps1:5 char:2\r\n+ (Get-VMSwitch -Id $DefaultVSwitchId).Name | Write-Output\r\n+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Get-VMSwitch], VirtualizationException\r\n    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch\r\n \r\n",)
                ***************************************************************
                
2019-06-04 18:36:36 ERROR    golem.node                          
                    There was a problem setting up the environment: No VM hypervisor found.
                    Golem will run with limited functionality to support
                    communication with local clients.
                    
2019-06-04 18:36:36 INFO     golem.node                          New account, waiting for password to be set. Run `golemcli account unlock` and enter
```
 
5. installation on clean state with toolbox available, pop-up (supporting hyperv) available, all hyperv boxes checked in windows features, , golem connect to nodes

**Comment by Wiezzel** [comment]
@ederenn @shadeofblue The "clean install, but Hyper-V pre-installed" scenario should work fine now. Please let me know if anything is wrong.

**Comment by ZmijaWA** [comment]
@Wiezzel @shadeofblue This: 

> installation on a clean state with HyperV preinstalled, no pop-up (supporting HyperV), HyperV boxes checked in windows features, a golem is not launching

Works fine -> Golem is launching and compute.

**Comment by Wiezzel** [comment]
@ZmijaWA Great.
Maybe check other scenarios again as well for regression.

**Pull request merged**
