### PR TITLE
Update installation scripts

### PR DESCRIPTION
**Pull request by banasiakadam60**
Signed-off-by: Adam Banasiak <banasiakadam60@gmail.com>

### CODE REVIEW

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by banasiakadam60** [comment]
We should merge it ASAP to `develop` and `b0.8.1`

**Review by jiivan — APPROVED** [review]

**Comment by banasiakadam60** [comment]
@mfranciszkiewicz Could you?

**Comment by banasiakadam60** [comment]
Tested on Ubuntu 14.04 and 17.04

**Comment by banasiakadam60** [comment]
Short description:

1. **LINUX**

- Add `-dev/--develop` switch to download packages from `dev` repo instead from main

- "Lazy initialization" - urls were intialized with downloaded json parsed in python. It tooks few seconds, and wasn't needed eg. when calling with `--help` and there's no situtation where we need all of them

- Install docker with apt - we don't need to update checksum anymore

- Fix files owner and permissions

2. **WINDOWS**

- Update `geth` to 1.7

**Review by mfranciszkiewicz — APPROVED** [review]

**Pull request merged**
