### PR TITLE
Install as admin

### PR DESCRIPTION
**Pull request by Wiezzel**
- [x] ⚠️  **FIXME: LocalAppDataFolder property points to admin's AppData folder**

### CODE REVIEW

**Review by shadeofblue — APPROVED** [review]

**Comment by mfranciszkiewicz** [comment]
Unfortunately `docker-machine` is bugged and doesn't properly handle `'` in directory names (#4073)

**Comment by Wiezzel** [comment]
@maaktweluit What was wrong with `USERNAME` property? It did work for me.

**Comment by maaktweluit** [comment]
@Wiezzel where did you see the `USERNAME` property?

The old code used `LogonUser`:
https://github.com/golemfactory/golem/pull/4064/files#diff-3ad93633a0b0cea71f784d796e8d15a1L13

It was not present in the new file, so i added it:
https://github.com/golemfactory/golem/pull/4064/files#diff-a06b451cd40ebfcbb43a69af732a35feR10

Then the property was filled with the admin name, so i set `RUNNING_USER` during the start of the installer and this worked for me

Nice info from AI: https://www.advancedinstaller.com/user-guide/user-information-props.html

**Comment by Wiezzel** [comment]
@maaktweluit I tried to use `USERNAME` here and you deleted it: https://github.com/golemfactory/golem/pull/4064/commits/17fa73fa688a5166ac0bda25075420db086bffc7#diff-a06b451cd40ebfcbb43a69af732a35feL4

But nevermind. I tested it again this morning with `USERNAME` and it didn't work while your solution works fine for me.

**Comment by maaktweluit** [comment]
AHHH, that is where it went! sorry, did not see that..

Good it works now, lets leave it :)

**Pull request merged**
