### PR TITLE
Change line endings in node.py

### PR DESCRIPTION
**Pull request by Krigpl**
sadasdasdasdasd

### CODE REVIEW

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by etam** [comment]
I don't see much reason in doing it now. It just makes it harder to browse the history of changes.

**Comment by tworec** [comment]
I agree with @etam. What is the purpose of this change?

**Comment by Krigpl** [comment]
So it's easier to review
https://github.com/golemfactory/golem/pull/2289/files#diff-1bef601c50a4151f88f0ecda16e1aa10

**Comment by etam** [comment]
"Oh, I spilled the milk. OK, from now on, the floor is supposed to be wet."

I also dislike that we have \r\n line endings in some files. On the other hand my Emacs has no problem with handling those files, so I don't even notice it. And making it harder to do `git blame` is a real problem. I think we just need to live with it.

**Comment by Wiezzel** [comment]
I'd suggest using [git-filter-branch](https://git-scm.com/docs/git-filter-branch) to remove all these \r\n endings from the history.

**Comment by Wiezzel** [comment]
Or maybe this can help: https://stackoverflow.com/a/47580886
For older Git version: https://stackoverflow.com/a/4683783

**Comment by etam** [comment]
607521caa - @mfranciszkiewicz it's your fault

**Review by etam — APPROVED** [review]

**Comment by Wiezzel** [comment]
@etam Using the proposal I linked could be completely transparent for `blame`. Just use the `-w` flag.

**Comment by maaktweluit** [comment]
@Wiezzel looks like an awesome fix, maybe we can make an issue to do this cleanup after this busy month

**Comment by etam** [comment]
@Wiezzel The thing is that there was earlier (about 2 weeks ago) a change of line endings, so the history is already destroyed. In this case I don't care anymore.

**Comment by Wiezzel** [comment]
@etam Is it? This is what I see when blaming `golem/node.py`:
```
4421eba5 golem/node.py        (Krigpl                2018-02-19 14:57:11 +0100   1) import logging
c7724df5 golem/node.py        (Piotr Chromiec        2018-02-23 13:41:05 +0100   2) from typing import List, Optional, Callable
0e15e444 examples/gnr/node.py (Paweł Bylica          2015-12-04 12:29:45 +0100   3) 
7048b776 golem/node.py        (Piotr Chromiec        2018-02-22 15:48:25 +0100   4) from twisted.internet import threads
c7724df5 golem/node.py        (Piotr Chromiec        2018-02-23 13:41:05 +0100   5) from twisted.internet.defer import gatherResults, Deferred
7048b776 golem/node.py        (Piotr Chromiec        2018-02-22 15:48:25 +0100   6) 
acb1d8d1 golem/node.py        (badb                  2016-12-02 17:04:44 +0100   7) from apps.appsmanager import AppsManager
6974c777 gnr/node.py          (Paweł Bylica          2016-06-30 16:06:30 +0200   8) from golem.client import Client
fd8e8d44 golem/node.py        (Piotr Chromiec        2018-02-20 15:35:54 +0100   9) from golem.clientconfigdescriptor import ClientConfigDescriptor
5fe8c677 golem/node.py        (Marek Franciszkiewicz 2018-02-28 16:56:02 +0100  10) from golem.core.deferred import chain_function
fd8e8d44 golem/node.py        (Piotr Chromiec        2018-02-20 15:35:54 +0100  11) from golem.core.keysauth import KeysAuth
5fe8c677 golem/node.py        (Marek Franciszkiewicz 2018-02-28 16:56:02 +0100  12) from golem.core.async import async_run, AsyncRequest
b6ae1c69 golem/node.py        (Marek Franciszkiewicz 2018-03-02 13:21:20 +0100  13) from golem.core.variables import PRIVATE_KEY
4421eba5 golem/node.py        (Krigpl                2018-02-19 14:57:11 +0100  14) from golem.docker.manager import DockerManager
fd8e8d44 golem/node.py        (Piotr Chromiec        2018-02-20 15:35:54 +0100  15) from golem.network.transport.tcpnetwork_helpers import SocketAddress
5fe8c677 golem/node.py        (Marek Franciszkiewicz 2018-02-28 16:56:02 +0100  16) from golem.report import StatusPublisher
cc685a8b golem/node.py        (Elfoniok              2017-11-03 13:32:33 +0100  17) from golem.rpc.mapping.rpcmethodnames import CORE_METHOD_MAP
4421eba5 golem/node.py        (Krigpl                2018-02-19 14:57:11 +0100  18) from golem.rpc.router import CrossbarRouter
5fe8c677 golem/node.py        (Marek Franciszkiewicz 2018-02-28 16:56:02 +0100  19) from golem.rpc.session import object_method_map, Session, Publisher
4326315e examples/gnr/node.py (badb                  2015-12-17 17:19:29 +0100  20) 
4421eba5 golem/node.py        (Krigpl                2018-02-19 14:57:11 +0100  21) logger = logging.getLogger("app")
4421eba5 golem/node.py        (Krigpl                2018-02-19 14:57:11 +0100  22) 
951e3480 gnr/node.py          (Artur Zawłocki        2016-01-12 14:09:23 +0100  23) 
7bcde4c0 golem/node.py        (Marek Franciszkiewicz 2018-03-02 12:39:26 +0100  24) # pylint: disable=too-many-instance-attributes
607521ca golem/node.py        (Marek Franciszkiewicz 2018-02-23 18:09:50 +0100  25) class Node(object):  # pylint: disable=too-few-public-methods
4326315e examples/gnr/node.py (badb                  2015-12-17 17:19:29 +0100  26)     """ Simple Golem Node connecting console user interface with Client
951e3480 gnr/node.py          (Artur Zawłocki        2016-01-12 14:09:23 +0100  27)     :type client golem.client.Client:
4326315e examples/gnr/node.py (badb                  2015-12-17 17:19:29 +0100  28)     """
4326315e examples/gnr/node.py (badb                  2015-12-17 17:19:29 +0100  29) 
```

**Comment by mfranciszkiewicz** [comment]
I broke the dam

**Comment by Krigpl** [comment]
shitsonfireyo

**Pull request merged**
