### PR TITLE
First draft on using dynamic memory for hyperv

### PR DESCRIPTION
**Pull request by maaktweluit**
Enable dynamic memory:
- Max memory is the configured max from app_cfg
- Min memory is the `MIN_CONSTRAINS[]` value
- Extended VMUtils to query max memory

### CODE REVIEW

**Review by Wiezzel — COMMENTED** [review]
My thoughts:
* I think it would be better to override `VMUtils.get_vm_summary_info()` to include an additional field in the result instead of introducing a new public method.
* Make sure to update `HyperVHypervisor._parse_create_params()` as well to have dynamic memory enabled and configured when creating the VM.

**Comment by maaktweluit** [comment]
@Wiezzel Thanks for the comments!

> I think it would be better to override VMUtils.get_vm_summary_info() to include an additional field in the result instead of introducing a new public method.

In the underlying library the vm_summary_info does not contain this data, that is why i opted to make a new function to get the `vm_memory_data`.
I think this also makes it easier to merge back to the upstream `os_win` library. ( https://github.com/openstack/os-win/compare/master...maaktweluit:master )

> Make sure to update HyperVHypervisor._parse_create_params() as well to have dynamic memory enabled and configured when creating the VM.

This was where i started, but these arguments are not available. The machine is always created with static minimum of 1GB, so i think this is OK.

**Comment by Wiezzel** [comment]
> This was where i started, but these arguments are not available. The machine is always created with static minimum of 1GB, so i think this is OK.

OK, so just remove the `--hyperv-disable-dynamic-memory` parameter.

**Comment by maaktweluit** [comment]
Good one! fixed :)

**Review by Wiezzel — APPROVED** [review]
👍

**Review by mfranciszkiewicz — APPROVED** [review]
LGTM, cannot test it though.

**Pull request merged**
