### PR TITLE
Move tools/ to golem/

### PR DESCRIPTION
**Pull request by chfast**
Git also changed line endings from CRLF to LF. Sorry.

It is small part of #71.

### CODE REVIEW

**Comment by chfast** [comment]
## [Current coverage](https://codecov.io/github/imapp-pl/golem?ref=42410c3d425e18c263ebc06209863e19091254c2) is `19.73%`

> Merging **#95** into **develop** will increase coverage by **+0.04%** as of [`42410c3`](https://codecov.io/github/imapp-pl/golem/commit/42410c3d425e18c263ebc06209863e19091254c2)

``` diff
@@            develop     #95   diff @@
=======================================
  Files           226     225     -1
  Stmts         18131   18094    -37
  Branches       1991    1985     -6
  Methods           0       0       
=======================================
  Hit            3570    3570       
  Partial          79      79       
+ Missed        14482   14445    -37
```

> Review entire [Coverage Diff](https://codecov.io/github/imapp-pl/golem/compare/9ae83a9c0a92c1449ad6e6be90b50cc929165f9d...42410c3d425e18c263ebc06209863e19091254c2) as of [`42410c3`](https://codecov.io/github/imapp-pl/golem/commit/42410c3d425e18c263ebc06209863e19091254c2)

---

### [Uncovered Suggestions](https://codecov.io/github/imapp-pl/golem/features/suggestions?ref=42410c3d425e18c263ebc06209863e19091254c2)
1. `+0.16%` via [...transport/message.py#1875...1903](https://codecov.io/github/imapp-pl/golem/golem/network/transport/message.py?ref=42410c3d425e18c263ebc06209863e19091254c2#1875) 
2. `+0.15%` via [.../task/pbrtgnrtask.py#66...93](https://codecov.io/github/imapp-pl/golem/examples/gnr/task/pbrtgnrtask.py?ref=42410c3d425e18c263ebc06209863e19091254c2#66) 
3. `+0.14%` via [...m/ranking/ranking.py#153...179](https://codecov.io/github/imapp-pl/golem/golem/ranking/ranking.py?ref=42410c3d425e18c263ebc06209863e19091254c2#153) 
4. _[See 7 more...](https://codecov.io/github/imapp-pl/golem/features/suggestions?ref=42410c3d425e18c263ebc06209863e19091254c2)_

> Powered by [Codecov](https://codecov.io). Updated on successful CI builds.

**Comment by badb** [comment]
I don't think it's the good idea to move it to golem. 
- `golem.nsi` should be moved outside, with setups, dockerfiles, etc. 
- Other files should be moved to `examples.tools`.
- Alternatively `make_package` may be left in `golem.tools`, but it's not really part of a Golem, it's just useful to copy golem files, for Update Other Golems task.

**Comment by chfast** [comment]
`examples` is not a valid package.
I can move it to `gnr` or `golem` (if are going to be used by other examples).

If we want to have other examples than gnr they need to be one-package or contain `setup.py` script as well. I would like to move `gnr` out of `examples` too.

**Comment by chfast** [comment]
@badb can you check now. That reflects our yesterday's discussion.

There is one more thing needed: creating package tree starting at `gnr.*`, instead of `examples.gnr.*` (GNR source can be moved then, but that is not required).

**Comment by badb** [comment]
Looks good, thanks. 

Maybe we should move `examples.tasks` to `gnr.task.code` or something similar?

**Pull request merged**
