### PR TITLE
use information from price oracle to display prices in USD

### LINKED ISSUE #848: Calculate payment fee in USD
We have payments in GNT and fees in ETH. But we also have GNT/ETH/USD price oracle. Use the oracle to calculate the fee as (USD/ETH)/(USD/GNT). We should also store USD prices in the database.

### PR DESCRIPTION
**Pull request by paulperegud**
resolves #848

### CODE REVIEW

**Comment by paulperegud** [comment]
Amount in USD is displayed in parenthesis

```
(golem-env) pawel@ppsh:~/code/ggolem/golem$ golemcli account
Golem_ID: 1bba1574cf2501219d370bbe06955ea092de253d026d2b73a6e5fbcb6049b2db820835f29c87ec9c54ba9ae352dff904f751c40c4ce89464badbe393f5a45da8
finances:
  available_balance: 1000.000000 GNT (22.21 USD)
  eth_address: '0xd8f1cdc8c18dfc3cc0df10ba162b2eb8fe2a2294'
  eth_balance: 0.999013 ETH (15.45 USD)
  reserved_balance: 0.000000 GNT (0.00 USD)
  total_balance: 1000.000000 GNT (22.21 USD)
node_name: ropsten@pepesza
provider_reputation: 0
requestor_reputation: 0
```

**Comment by paulperegud** [comment]
Current state: balances are displayed also in USD.

TODO: display incomes and prices in USD

**Comment by subtly** [comment]
Thoughts on moving this to the frontend?  (Notably, it requires external connectivity to 3rd-party which user will want control over)

**Comment by paulperegud** [comment]
@subtly good point. I've talked with @mdtanrikulu and @chfast about it and they also agree that this stuff should not be in the core.

**Pull request closed without merging**
