### PR TITLE
logs hardware preset fx

### LINKED ISSUE #2374: hardware preset logs not same as gui
When saving a new hardware preset, for example:

screen shot 2018-03-15 at 17 04 20

then apply it, the logs show:
```
2018-03-15 17:04:29 INFO     golem.core.hardware                 updating config: name: test, num_cores: 7, max_memory_size: 12.0 MiB, max_resource_size: 32.7 MiB
```

Related to https://github.com/golemfactory/golem-electron/issues/251

### PR DESCRIPTION
**Pull request by tworec**
fixes #2374

### CODE REVIEW

**Comment by tworec** [comment]
Seems that we store mem and disk in KiB

```
$ golemcli settings set 2>&1 | grep max
	max_resource_size                                    int > 0 [kB]	Maximal resource size
	max_price                                              float >= 0	Max GNT/h price (requestor)
	max_memory_size                    16777216 > int >= 1024000 [kB]	Max memory size
```

https://github.com/golemfactory/golem/blob/efae6fe40390091f6d7b13bb655726513ed228f7/golem/interface/client/settings.py#L61-L63

https://github.com/golemfactory/golem/blob/efae6fe40390091f6d7b13bb655726513ed228f7/golem/interface/client/settings.py#L140-L141

**Comment by tworec** [comment]
TODO: 
- [x] - check how preset influence docker
- [x] - check task (sub)task acceptance based on available provider resources

**Review by maaktweluit — COMMENTED** [review]
LGTM!

Will not approve with open TODO's, they could be separate PR / Issues.

**Comment by tworec** [comment]
@maaktweluit TODOs checked

**Review by mfranciszkiewicz — APPROVED** [review]

**Review by maaktweluit — APPROVED** [review]

**Pull request merged**
