### PR TITLE
Decrease transitions loglevel

### PR DESCRIPTION
**Pull request by jiivan**

### CODE REVIEW

**Comment by etam** [comment]
Do you have an example of before and after?

**Review by kmazurek — APPROVED** [review]
go_go_go

**Comment by jiivan** [comment]
> Do you have an example of before and after?

Before:
```
INFO [transitions.core                   ] Exited state initial
INFO [transitions.core                   ] Entered state handshaking
INFO [transitions.core                   ] Exited state handshaking
INFO [transitions.core                   ] Entered state connected
```
After:
```
```

**Comment by etam** [comment]
> Do you have an example of before and after?

I have. Here it is: https://github.com/golemfactory/golem/pull/5109#issuecomment-595179599

**Review by etam — APPROVED** [review]
ok

**Pull request merged**
