### PR TITLE
Moved quotes from lintdiff.sh to circle.yml to expand later

### LINKED ISSUE #1309: mypy fails when adding new files to root
https://circleci.com/gh/golemfactory/golem/5302

```
$ ./lintdiff.sh mypy apps golem gui scripts setup_util tests *.py
...
mypy apps golem gui scripts setup_util tests conftest.py golemapp.py golemcli.py loggingconfig.py setup.py
mypy: can't read file 'conftest.py': No such file or directory
...
```

I think the expand of `*.py` happens at the wrong moment. 
It should be expanded at run-time, after checkout develop, and not at call-time on the working branch.

### PR DESCRIPTION
**Pull request by maaktweluit**
Resolves #1309

### CODE REVIEW

**Comment by marmistrz** [comment]
What's the problem with quotes expanding eagerly?

**Comment by maaktweluit** [comment]
It can not lint new files on the working branch: file is not found when it switches to develop.
See related issue for a linked build and logs

**Review by marmistrz — APPROVED** [review]
LGTM

**Review by badb — APPROVED** [review]

**Comment by marmistrz** [comment]
@maaktweluit I've just realized this will break if there's any `*.py` file containing a space. I'll tackle this in #1312

**Comment by maaktweluit** [comment]
@marmistrz nice catch! when mypy or pylint can expand the * its even better!

**Pull request merged**
