### PR TITLE
Improved checking Hyper-V status on Windows

### PR DESCRIPTION
**Pull request by kmazurek**
Resolves: #4024

Updated the relevant Powershell script to use the field
HypervisorPresent from Win32_ComputerSystem WMI object. This provides a
more reliable way of determining hypervisor availability on the system.

### CODE REVIEW

**Review by Wiezzel — CHANGES_REQUESTED** [review]
`HypervisorPresent` is true even if hypervisor service is not running.

**Comment by kmazurek** [comment]
Ok, I'll keep the check for `vmms` process running. However, from my testing `HypervisorPresent` covers more cases than the call to `Get-Module -ListAvailable hyper-v`. I'm going to replace the latter with the former in the script.

**Comment by Wiezzel** [comment]
@zakaprov Maybe instead of this try-catch do this:
```powershell
(Get-Service -Name vmms).Status -Eq "Running"
```

**Comment by Wiezzel** [comment]
And you could also check `vmcompute` service.

**Comment by kmazurek** [comment]
@Wiezzel Good one, thanks. I might still need to wrap the call to `Get-Service` in a try-catch since these services may not be present on a fresh system. Will try to verify that.

**Review by Wiezzel — COMMENTED** [review]
If `$IsHypervisorPresent` is `False` the script should return `False`.

**Comment by kmazurek** [comment]
@Wiezzel It does return `False`, the last line of the script got conveniently truncated in the GitHub changes viewer.

**Review by Wiezzel — APPROVED** [review]

**Pull request merged**
