### PR TITLE
Remove description box from Accounts

### PR DESCRIPTION
**Pull request by matthewsedam**
Issue #934. This removes the description box from the Accounts section in the old GUI as well as code associated with a node's description.

### CODE REVIEW

**Comment by matthewsedam** [comment]
The Appveyor build timed out.

**Review by badb — APPROVED** [review]
LGTM, thanks for contibuting!

**Comment by badb** [comment]
@jiivan Please check if doesn't need any changes on monitor side. We can merge it after you give your accept.

**Review by jiivan — APPROVED** [review]
No monitor changes are needed.

**Comment by badb** [comment]
@matthewsedam Can you please do merge / rebase one last time? This one is ready to be merged after that.

**Comment by matthewsedam** [comment]
@badb I have merged develop into this. Would you like me to rebase this into one commit?

**Pull request merged**
