### PR TITLE
Upgrade to web3 v4

### LINKED ISSUE #2366: deprecated in favor of an upcoming v4 method: eventFilter()
Since release `0.13.0` in all logs:
```
2018-03-06 15:30:35 WARNING  py.warnings                         /python3.6/site-packages/web3/utils/decorators.py:17: DeprecationWarning: on is deprecated in favor of an upcoming v4 method: eventFilter()
  return self.method(obj, *args, **kwargs)
```

Please investigate and resolve.

### PR DESCRIPTION
**Pull request by Krigpl**
what-could-possibly-go-wrong_o_5802169

Fixes #2366

### CODE REVIEW

**Comment by Krigpl** [comment]
Will make SCI release and update this PR after it gets approved.

**Comment by Krigpl** [comment]
ping

**Review by maaktweluit — APPROVED** [review]
LGTM!

This could happen:
wrong

**Comment by mfranciszkiewicz** [comment]
`Golem-Smart-Contracts-Interface==2.1.0` or `1.2.0`?

**Comment by Krigpl** [comment]
> Golem-Smart-Contracts-Interface==2.1.0 or 1.2.0?

Yes

**Review by mfranciszkiewicz — APPROVED** [review]

**Pull request merged**
