### PR TITLE
parallel lint

### PR DESCRIPTION
**Pull request by tworec**
this speeds local checks 8x for me :) but I don't know how do it impact build bots

### CODE REVIEW

**Review by ktomala — APPROVED** [review]
Ok for me

**Review by maaktweluit — APPROVED** [review]
LGTM!

On buildbots i see a 2 minute win, great!
Think this is due to less cores on buildbots then on your machine ;)

**Comment by maaktweluit** [comment]
triggered re-build of appveyor now it has approvals

**Review by badb — APPROVED** [review]

**Comment by tworec** [comment]
Thanks @ktomala @maaktweluit for your reviews, thanks @badb for mergeing

Now I see that this should be implemented in `.pylintrc`. I'll make another PR with fix

**Pull request merged**
