### PR TITLE
(sub)task_id uniqueness 

### LINKED ISSUE #1926: Subtask IDs should be unique within a single Requestor
I don't know if it's the case right now, but if it's not then it should be.

### PR DESCRIPTION
**Pull request by tworec**
resolves #1926

### CODE REVIEW

**Comment by Krigpl** [comment]
I wouldn't say that change resolves any of those two mentioned issues.
~In case of #1926 this change makes it even worse. This issue is about making sure that single requestor won't generate two identical IDs. When creating new subtask Golem should check that it's ID hasn't been used previously, simply by checking the DB.~
Ok, I didn't realize uuid1 encodes current timestamp with quite large precision. In that case it makes it reasonable here.
And in case of #2211 it's about making sure that we use pair `requestor_id, subtask_id` when identifying subtasks. Using uuid1 instead of uuid4 doesn't change anything in this regard.

**Comment by tworec** [comment]
sorry @Krigpl this is WIP, simply putted @ GH to be able to continue work from another machine :)

**Comment by shadeofblue** [comment]
@tworec it's a step towards a good direction but as @Krigpl said, it doesn't resolve anything with regards to the second issue for two reasons:
1) someone might still generate a colliding `task_id` + `subtask_id`
2) it doesn't resolve an issue of a perfectly normal task flow where one Provider fails the task and another Provider takes it -> since, if the `subtask_id` stays the same, the first Provider's message exchange history may still interfere with the second one's history ... we'd need to identify those messages using not only the subtask id but also the node the messages were exchanged with

**Comment by tworec** [comment]
@shadeofblue as I said, this is draft, a WIP commit only. It's current shape will highly evolve. I didn't ask for review.... ;)  

My plan was to implement solution discussed with @jiivan and described here: https://github.com/golemfactory/golem/issues/2211#issuecomment-371785739

**Comment by tworec** [comment]
guys @Krigpl and @shadeofblue, I've changed solution conception: lets use `public_key` as a node for `uuid1` generation. Code presents it only for `task_id`. If you like it, I will change also `subtask_id` generation.

**Review by shadeofblue — APPROVED** [review]
lgtm

**Review by jiivan — COMMENTED** [review]
I like the idea of using part of `node_id` as an initializer for `uuid1` but it still won't guarantee uniqueness (because part of node_id could collide).

**Review by jiivan — APPROVED** [review]
I we verify those 6 bytes upon receiving task/subtask, then it would be better than current implementation.

**Comment by tworec** [comment]
- task_id is generated as uuid1 with node (low 48 bits) set to top 48 bits from public key
- subtask_id is generated with node (low 48 bits) set to task_id node (low 48 bits)

So (sub)task_id's can be verified by `golem-messages` to match requestor public key. This enforces uniqueness betweeen requestors (to produce malicious collision attacker need to generate public key with same top48 bits wich needs ~32k cpu years, and this will allow only to disturb single node on the network).

Use of uuid1 ensures uniqueness within requestor.

**Pull request merged**
