### PR TITLE
Update to Blender version 2.79

### LINKED ISSUE #1849: Update Blender version to 2.79
We're using 2.78 i Dockerfiles right now. New version has additional features for GPU rendering, which may be useful in the future.

### PR DESCRIPTION
**Pull request by Wiezzel**
Is that all?

Closes #1849

### CODE REVIEW

**Comment by maaktweluit** [comment]
Not sure if this is still used, but its also here:
https://github.com/golemfactory/golem/blob/c2c20539ed048a8fbafebd14000352bb073df097/tests/apps/blender/resources/stdout.log_for_test

**Comment by Wiezzel** [comment]
@maaktweluit I can update the log just to keep things in order, but TestBlenderLogAnalyser passes without any updates to this file.

**Comment by maaktweluit** [comment]
Strange! maybe its not used at all, @badb do you know if this file is still needed?

**Comment by Wiezzel** [comment]
@maaktweluit This file is read here: https://github.com/golemfactory/golem/blob/develop/tests/apps/blender/resources/test_blenderloganalyser.py It's just that the version is ignored.

**Comment by badb** [comment]
We should generate a similiar log for Blender 2.79 to make sure that log format is not change.

**Review by Elfoniok — CHANGES_REQUESTED** [review]
Pleas rebuild docker images and public them on docker hub. Otherwise this change doesn't make sense.

**Comment by Wiezzel** [comment]
Btw, I just realized that 2.79a is a release candidate, so we need just 2.79.

**Comment by Wiezzel** [comment]
@Elfoniok I have successfully built new docker image and pushed it to docker hub. The image version was also updated in all files. Please review.

**Review by Elfoniok — APPROVED** [review]
LGTM

**Comment by badb** [comment]
Multi-OS test scenarios on this branch should be done by @ederenn before we can merge it.

**Comment by Wiezzel** [comment]
@badb Yep, they are in progress, as far as I know.

**Pull request merged**
