### PR TITLE
Set headers visible and changed their order

### PR DESCRIPTION
**Pull request by magdasta**
#619

### CODE REVIEW

**Comment by mfranciszkiewicz** [comment]
The `progress` column takes more than half of the view after maximizing the window. Perhaps some reordering / width scaling would help?

**Comment by paulperegud** [comment]
@mfranciszkiewicz @magdasta  This PR is hanging here for a long time. Have you decided on how to proceed?

**Comment by mfranciszkiewicz** [comment]
@paulperegud Not really. Feel free to make changes.

**Comment by mfranciszkiewicz** [comment]
I took the liberty of changing the resize behavior. Users can now resize columns manually.

**Review by paulperegud — APPROVED** [review]
LGTM

**Comment by badb** [comment]
One small potential problem: if user resize one column manually, than those changes are lost aftert window is resized. Anyway, it's probably not very important and this is much better than current "solution" .

**Pull request merged**
