### PR TITLE
No gui

### PR DESCRIPTION
**Pull request by maaktweluit**
Removed all gui related files, dependencies and logic.

Moved `gui/controller/memoryhelper.py` → `golem/tools/memoryhelper.py`. Please advise on the best location.

Ran a build on my fork successfully: https://ci.appveyor.com/project/maaktweluit/golem/build/no_gui-25

- [x] remove jsonpicke from requirements

Solves:
```
_______________ ERROR collecting tests/golem/rpc/test_router.py ________________
tests/golem/rpc/test_router.py:7: in <module>
    from golem.rpc.router import CrossbarRouter
golem/rpc/router.py:6: in <module>
    from crossbar.controller.node import Node
.venv/lib/python3.5/site-packages/crossbar/controller/node.py:66: in <module>
    from crossbar.controller.process import NodeControllerSession
.venv/lib/python3.5/site-packages/crossbar/controller/process.py:60: in <module>
    from crossbar.common.fswatcher import HAS_FS_WATCHER, FilesystemWatcher
.venv/lib/python3.5/site-packages/crossbar/common/fswatcher.py:37: in <module>
    from watchdog.observers import Observer
.venv/lib/python3.5/site-packages/watchdog/observers/__init__.py:63: in <module>
    from .inotify import InotifyObserver as Observer
.venv/lib/python3.5/site-packages/watchdog/observers/inotify.py:74: in <module>
    from .inotify_buffer import InotifyBuffer
.venv/lib/python3.5/site-packages/watchdog/observers/inotify_buffer.py:20: in <module>
    from watchdog.observers.inotify_c import Inotify
.venv/lib/python3.5/site-packages/watchdog/observers/inotify_c.py:50: in <module>
    libc = _load_libc()
.venv/lib/python3.5/site-packages/watchdog/observers/inotify_c.py:42: in _load_libc
    return ctypes.CDLL(libc_path)
/usr/lib/python3.5/ctypes/__init__.py:347: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_time_unref
```

### CODE REVIEW

**Comment by marmistrz** [comment]
This commit should remove `jsonpickle` from requirements, since the only left occurence is in the gui due to #1254

**Comment by maaktweluit** [comment]
good one! will do it when i get home tonight!

**Comment by maaktweluit** [comment]
Closing, will be merged in #1487

**Comment by maaktweluit** [comment]
Whoops, thought i closed it 18h ago...

**Pull request closed without merging**
