### PR TITLE
Update urllib3 to 1.24.3

### PR DESCRIPTION
**Pull request by kmazurek**

### CODE REVIEW

**Review by shadeofblue — APPROVED** [review]
peaches on a tree

**Comment by shadeofblue** [comment]
ah @zakaprov you need to also modify the `requirements***to-freeze`

**Comment by kmazurek** [comment]
Currently the build is failing due to `requests` depending on an older version of `urllib3`. Support for 1.25+ seems to be [in the works](https://github.com/kennethreitz/requests/tree/urllib1.25). I'm going to wait for this to be merged before proceeding here.

**Comment by kmazurek** [comment]
`urllib3` now includes a `1.24.3` patch release which addresses the relevant security issue (as per [this](https://github.com/kennethreitz/requests/issues/5067#issuecomment-488729843) comment). I have updated the changes to use this version of the library.

**Pull request merged**
