### PR TITLE
Preserve geth and hyperg logs

### PR DESCRIPTION
**Pull request by paulperegud**
This is a part of effort of making logs more useful.
Uses tee and Tee-object on Windows (via Powershell).

Side effect - tee strips colors from geth output.

TODO:

- [x] geth linux
- [x] geth mac
- [x] geth windows
- [x] hyperg linux
- [x] hyperg mac
- [x] hyperg windows

### CODE REVIEW

**Comment by jiivan** [comment]
About geth team attitude to logging: https://ethereum.stackexchange.com/questions/3229/geth-what-happened-to-logfile

**Comment by paulperegud** [comment]
@jiivan 
```
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]: Traceback (most recent call last):
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:     self.run()
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:   File "/usr/lib/python3.5/threading.py", line 862, in run
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:     self._target(*self._args, **self._kwargs)
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:   File "/home/ubuntu/golem/golem/utils.py", line 82, in tee_target
Aug 18 13:04:15 ip-172-31-55-106 golemapp[17001]:     out.write(prefix + line)
```

**Comment by banasiakadam60** [comment]
LGTM, but didn't tested

**Review by badb — COMMENTED** [review]
@paulperegud Can you make a rebase? 
Geth logs seems to work properly but hyperg logs are never created - should I change something else to activate them?

**Comment by jiivan** [comment]
Please use hyperg v2

**Comment by badb** [comment]
@paulperegud or @jiivan merge / rebase, please.

**Review by banasiakadam60 — APPROVED** [review]

**Review by banasiakadam60 — APPROVED** [review]
LGTM

**Pull request merged**
