### PR TITLE
Environment 'ERROR' status

### PR DESCRIPTION
**Pull request by Wiezzel**

### CODE REVIEW

**Comment by mfranciszkiewicz** [comment]
It would be helpful to know the reason why the error occurred

**Comment by Wiezzel** [comment]
@mfranciszkiewicz The exception is always logged and re-raised. So the caller will have their reason.

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by mfranciszkiewicz** [comment]
I guess this will suffice. To be clear: the point was to store the reason with the status so it can be queried later on.

**Comment by Wiezzel** [comment]
@mfranciszkiewicz I see. If this is needed we might think of adding it later on. But AFAIK Python enums don't support storing any additional data so it would require some more substantial changes to the way statuses are represented.

**Review by Krigpl — APPROVED** [review]

**Pull request merged**
