### PR TITLE
Removing pause and restart task

### PR DESCRIPTION
**Pull request by cr44d**

### CODE REVIEW

**Review by badb — CHANGES_REQUESTED** [review]
Why did you remove code for restart task as well? This one was needed.

**Comment by cr44d** [comment]
@badb sorry for that, for some reason I thought this was the same as resuming paused tasks. Will fix it ASAP.

**Comment by cr44d** [comment]
@badb just "unremoved" restarting
But I've got a question about `golem/client.py`, should I remove methods `pause` and `resume`?

**Review by badb — APPROVED** [review]

**Comment by badb** [comment]
@cr44d Can you accept the CLA?

**Pull request merged**
