### PR TITLE
node_integration_tests: lowered the comp.tasks timeout from 60 to 2 minutes

### PR DESCRIPTION
**Pull request by maaktweluit**
Creating a task should never take this long

### CODE REVIEW

**Review by Wiezzel — APPROVED** [review]
Sure, why not.

**Review by shadeofblue — APPROVED** [review]
may slightly increase output clutter but agree with the premise ... 

might I suggest an intermediate value of e.g. 3 seconds sleep?

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by maaktweluit** [comment]
@shadeofblue no extra clutter for me, it already gets the task the first time, so normally the timer is not even used.

Why 3 seconds over 1? happy to change it for a good cause :)

**Comment by shadeofblue** [comment]
@maaktweluit I was just concerned that if - in some cases - the creation takes e.g. half a minute, you'd get 30 messages ... which seems undesirable ..

**Comment by maaktweluit** [comment]
@shadeofblue thanks, updated :)

**Pull request merged**
