### PR TITLE
new argument '--nomonitor', issue #876

### PR DESCRIPTION
**Pull request by maaktweluit**
Hey Golem,

For issue #876 this morning there was a perfect test, the monitor server was offline.
So i was able to add the argument `--nomonitor` and test it on ubuntu 16.04 server and desktop.
No more errors!

Please let me know if there is anything i can add to make this pull request better.

Have a good one!

Maaktweluit

### CODE REVIEW

**Comment by maaktweluit** [comment]
Rebased this branch onto develop after conflicts appeared.

**Review by jiivan — APPROVED** [review]
LGTM

**Comment by maaktweluit** [comment]
Rebased for conflicts

**Review by badb — APPROVED** [review]
LGTM

**Pull request merged**
