### PR TITLE
Fix GLambda benchmark

### PR DESCRIPTION
**Pull request by mplebanski**
Fixes https://github.com/golemfactory/golem/issues/4301

### CODE REVIEW

**Comment by Krigpl** [comment]
You should at least link the issue, but ideally, any more descriptive summary should be included.

**Review by Krigpl — CHANGES_REQUESTED** [review]
Putting `ENV HOME=/home/user` in the GLambda Dockerfile works for me, please check that.

**Comment by mplebanski** [comment]
> Putting `ENV HOME=/home/user` in the GLambda Dockerfile works for me, please check that.

This is related to how we launch docker, why put it in Dockerfile?

**Comment by Krigpl** [comment]
> This is related to how we launch docker, why put it in Dockerfile?

Why is this specific to GLambda?

**Comment by mplebanski** [comment]
> > This is related to how we launch docker, why put it in Dockerfile?
> 
> Why is this specific to GLambda?

Because the runtime container is different.

**Review by Krigpl — APPROVED** [review]
This is also setting the `HOME` to a nonexistent directory. It'd be great to put any kind of comment in the code why does it is even needed there.

**Review by Krigpl — APPROVED** [review]
That looks good.

**Pull request merged**
