### PR TITLE
Move hardware mixin to node

### PR DESCRIPTION
**Pull request by maaktweluit**
So the RPC functions are available before the client is started

This way when docker crashes the GUI can change the preset

### CODE REVIEW

**Comment by Wiezzel** [comment]
Why?

**Comment by maaktweluit** [comment]
@Wiezzel updated description, does this answer your question?

**Comment by Wiezzel** [comment]
@maaktweluit Yep, sure. Maybe update the commit message as well?

**Comment by maaktweluit** [comment]
good one, done

**Review by mfranciszkiewicz — APPROVED** [review]

**Review by Wiezzel — APPROVED** [review]

**Pull request merged**
