### PR TITLE
LoopingCallService sync by default

### LINKED ISSUE #2851: LoopingCallService with optional separate thread
Make it possible for `LoopingCallService` to execute `_run` in the same thread.

Refer to https://github.com/golemfactory/golem/pull/2849

### LINKED ISSUE #3245: cannot identify image file - current_task_preview
#### Encountered on:
Mac OS GOLEM Version: 0.17.0+dev99.g6d235f1

during computations of a task: helicopter.blend 400x400 10 frames 30 subtasks, 4 subtask had been left uncomputed

in `golem.log`

```
2018-08-28 18:53:36 ERROR    golem.client                        task_server.sync_network failed
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 1485, in _run
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 140, in sync_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 881, in __remove_old_tasks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 787, in check_timeouts
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/common.py", line 147, in func_wrapper
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 131, in computation_failed
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 338, in _update_frame_task_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 452, in __mark_sub_frame
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 354, in _open_frame_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/PIL/Image.py", line 2519, in open
OSError: cannot identify image file '/Users/a/Library/Application Support/golem/default/mainnet/res/64301ada-aae1-11e8-837b-7c3ec369ac11/tmp/current_task_preview1.PNG'
```

```
018-08-28 18:53:38 ERROR    golem.client                        task_server.sync_network failed
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 1485, in _run
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 140, in sync_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 881, in __remove_old_tasks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 787, in check_timeouts
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/common.py", line 147, in func_wrapper
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 131, in computation_failed
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 338, in _update_frame_task_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 452, in __mark_sub_frame
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 354, in _open_frame_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/PIL/Image.py", line 2519, in open
OSError: cannot identify image file '/Users/a/Library/Application Support/golem/default/mainnet/res/64301ada-aae1-11e8-837b-7c3ec369ac11/tmp/current_task_preview8.PNG'
```

```
2018-08-28 18:54:00 ERROR    golem.client                        task_server.sync_network failed
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 1485, in _run
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 140, in sync_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 881, in __remove_old_tasks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 787, in check_timeouts
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/common.py", line 147, in func_wrapper
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 131, in computation_failed
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 338, in _update_frame_task_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 452, in __mark_sub_frame
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 354, in _open_frame_preview
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/PIL/Image.py", line 2519, in open
OSError: cannot identify image file '/Users/a/Library/Application Support/golem/default/mainnet/res/64301ada-aae1-11e8-837b-7c3ec369ac11/tmp/current_task_preview4.PNG'
```

```
018-08-28 18:54:03 CRITICAL twisted                             An exception was raised from application code while processing a reactor selectable
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/kqreactor.py", line 293, in _doWriteOrRead
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpnetwork.py", line 340, in dataReceived
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpnetwork.py", line 366, in _interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 123, in interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 76, in interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 485, in _react_to_want_to_compute_task
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 396, in get_next_subtask
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 484, in query_extra_data
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 338, in _update_frame_task_preview
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 452, in __mark_sub_frame
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 354, in _open_frame_preview
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/PIL/Image.py", line 2519, in open
    
builtins.OSError: cannot identify image file '/Users/a/Library/Application Support/golem/default/mainnet/res/64301ada-aae1-11e8-837b-7c3ec369ac11/tmp/current_task_preview3.PNG'
```
from res folder:

current_task_preview1

current_task_preview3

current_task_preview4

current_task_preview8

current_task_preview9

### LINKED ISSUE #3660: fix race conditions caused by LoopingCallService running in separate threads
Every `LoopingCallService` in `golem/client.py` runs in a separate thread, through `twisted.internet.threads.deferToThread`. But there are no measures preventing race conditions.

This caused problems before: #2849 
This causes problems now: #3245 

There is an issue to make easy to optionally to run `LoopingCallService` in main thread: #2851 

Possible solution: run `LoopingCallService` by default in main thread and optionally in a separate thread. This needs little changes in code, but requires extensive performance testing.

### LINKED ISSUE #5083: SubtaskResultsAccepted lost when running wasm integration tests
## Description

**Golem Version**: current develop (10aebd5a0), but was observed for quite a while.

**Golem-Messages version**: 3.15.0

**OS**: Linux

**Branch**: develop

**Description of the issue**:

When running wasm verification by redundancy integration tests, `SubtaskResultsAccepted` message seems to be lost in transport.

## Steps To Reproduce

Run wasm_vbr_single_failure integration test.

### PR DESCRIPTION
**Pull request by etam**
For these services I think it's OK to let them run in threads:
- TaskArchiverService
- ResourceCleanerService

fixes #3660 
fixes #3245 
resolves #2851 
fixes #5083

### CODE REVIEW

**Comment by mplebanski** [comment]
Why do you think it is safe to run TaskArchiver service in a separate thread? By looking at `do_maintenance` method it is no so clear to me.

**Comment by mplebanski** [comment]
Same question for `ResourceCleanerService`. It is using the same `dir_manager` that is used by the golem apps arbitrarily.

**Comment by etam** [comment]
> Why do you think it is safe to run TaskArchiver service in a separate thread? By looking at `do_maintenance` method it is no so clear to me.

Ok, I had a closer look at it, and it's not thread safe. But very little work is required to make it so, so I'll do it.

**Comment by etam** [comment]
> Same question for `ResourceCleanerService`. It is using the same `dir_manager` that is used by the golem apps arbitrarily.

No, it calls `remove_distributed_files` and `remove_received_files`, which are creating their own instances of `DirManager` and are just removing files from filesystem. There's an issue to make it more safe #2432, but from threading point of view, I see no problem here.

**Comment by mplebanski** [comment]
Did you have a chance to run it and check performance behavior?

**Comment by etam** [comment]
> Did you have a chance to run it and check performance behavior?

Yes and it seems that it's working good.

**Review by mplebanski — APPROVED** [review]

**Review by mfranciszkiewicz — DISMISSED** [review]
`DoWorkService` will now be called every second in the main thread. Please profile it when Golem is under load, since that service used to be a big performance hit.

**Comment by mplebanski** [comment]
Are we going to merge that or not?

**Comment by etam** [comment]
I'm working on properly profiling golem. It means I need to learn a bit of this stuff. When I'm done I'll share my results and write a guide for others.

**Comment by mplebanski** [comment]
Awesome.

**Comment by etam** [comment]
The same change, but rebased onto b0.22 is in branch LoopingCallService_sync_by_default_b0.22

**Comment by jiivan** [comment]
IMvHO it this change looks promising. Were there any conclusions from profiling/running under load?

**Comment by etam** [comment]
I didn't got to testing under serious load (like mainnet network), because I was moved to other tasks back then. Now our QA team is testing this (but without profiling), to check if there are any regressions.

**Pull request merged**
