### PR TITLE
Fixed `remaining` in `golemcli tasks show`

### LINKED ISSUE #2272: `golemcli tasks show` no remaining?
It looks like there are always 0 tasks remaining, looking at the total % this should not be the case:

```
golemcli tasks show
id                                      remaining    subtasks  status     completion
------------------------------------  -----------  ----------  ---------  ------------
a1e5b01d-f5b2-43b0-9910-3ed311efb155            0          33  Computing  87.88 %

```

### PR DESCRIPTION
**Pull request by Wiezzel**
Renamed the column to 'ETA' and added time formatting. Also got rid of -0.0 which seemed like a very hacky way to mark missing value.

Looks like this:
```
id                                    ETA        subtasks  status     completion
------------------------------------  -------  ----------  ---------  ------------
60ce8f9c-37ef-11e8-bce7-6478de4573b1  0:00:00          10  Finished   100.00 %
dabd4382-380f-11e8-83b6-6478de4573b1  0:02:45          10  Computing  80.00 %
```

Close #2272

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM!

Good find on the always 0 !

**Comment by maaktweluit** [comment]
Rebuild appveyor

**Comment by Wiezzel** [comment]
@maaktweluit It's rebuilding. :)

**Review by mfranciszkiewicz — APPROVED** [review]
LGTM

**Pull request merged**
