### PR TITLE
Revert "Enable json serializer in crossbar router"

### PR DESCRIPTION
**Pull request by etam**
This reverts commit 51d8a97c25fb9ddf7ffa2a237d5cce85372e57f9.

This was introduced in #3926, but it's not needed anymore.

### CODE REVIEW

**Comment by shadeofblue** [comment]
@etam please rebase that against `develop` -> it's not important for this release

**Comment by etam** [comment]
rebased

**Review by kmazurek — APPROVED** [review]
keanu_ok

**Review by shadeofblue — APPROVED** [review]

**Comment by etam** [comment]
Somehow this change is making integration tests fail with `ReactorAlreadyInstalledError`. I can reproduce this on my PC.

**Comment by etam** [comment]
It fails, because I removed importing `golem.rpc.router` from `golemapp.py`. Which is totally weird and it shouldn't behave like that.

**Comment by etam** [comment]
I pinned down a bit this twisted weird behavior: In `golem/network/hyperdrive/client.py` there is `from twisted.web.client import readBody`, which internally does `from twisted.internet import [...] reactor`. This installs default reactor. Somehow importing `golem.rpc.router` in `golemapp.py` inhibits installing reactor.

Edit: `import golem.rpc.router` can be replaced by more precise `import crossbar.personality`.

**Comment by mfranciszkiewicz** [comment]
@etam Also `from twisted.web.client import readBody` can be safely converted to a local import in `_async_request`

**Comment by etam** [comment]
> @etam Also `from twisted.web.client import readBody` can be safely converted to a local import in `_async_request`

This seems to be not enough. I've made a workaround for now. Let's resolve this in a separate task.

**Pull request merged**
