### PR TITLE
Remove too-few-public-methods pylint warning

### PR DESCRIPTION
**Pull request by Krigpl**
Because it's only annoying

### CODE REVIEW

**Review by Elfoniok — APPROVED** [review]

**Review by Wiezzel — APPROVED** [review]
👏

**Comment by mplebanski** [comment]
`R: tests/golem/network/concent/test_received_handler.py:460:0: Too few public methods (1/2) (too-few-public-methods)\n`

**Comment by etam** [comment]
Shouldn't you also remove `noqa`?

**Comment by Krigpl** [comment]
@etam 
I removed all those comments via script so didn't cover those special cases.

**Pull request merged**
