### PR TITLE
Remove PyTaskThread

### PR DESCRIPTION
**Pull request by Krigpl**
And one of the DummyTasks that were using it.
This also enables further cleanup.

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM!

Nice cleanup

**Review by mfranciszkiewicz — CHANGES_REQUESTED** [review]
- `test_dummy_task_computation` fails on macOS
- `test_dummy_task_computation` will no longer be run on windows and macOS buildbot workers (no Docker)

**Comment by jiivan** [comment]
@Krigpl is this still relevant?

**Comment by Krigpl** [comment]
@jiivan Somewhat. This change requires an ability to use Docker on macos/windows buildbots, something that is not supported right now, but @maaktweluit is looking into that.

**Comment by mplebanski** [comment]
Shall we revive this refactor?

**Pull request closed without merging**
