### PR TITLE
[WIP] Cli test task and update task save file with results

### PR DESCRIPTION
**Pull request by maaktweluit**
Working on #823 
This was assisted by #1352 
This issue should fix testing a task save file and storing the results / errors.

This PR contains a set of useful functions waiting to be put on the proper spot in the project:
- [ ] load file from default saves location
- [ ] check if file is writable
- [ ] test and default blender task resolution
- [ ] test and default blender task frames
- [ ] test and default (blender) task output name
- [ ] save tested task_def to file ( needs better UX )

Probably some of these are already there, please advise where to put the rest, if any.

### CODE REVIEW

**Comment by marmistrz** [comment]
Can we close it due to #1331?

**Comment by maaktweluit** [comment]
@marmistrz we can remove the "create" part from this issue and only keep the "test and save default values to task file".
Will update the title to be more clear.

When #1331 is finished i'll rebase and continue on this PR

**Comment by marmistrz** [comment]
Anyway, this commit is a no-go even if you remove the *create* part due to usage of jsonpickle, which is possibly dangerous and was removed #1254.

**Comment by maaktweluit** [comment]
closing this PR because it is stale for a year.

We can use the branch as reference when we pick up #823 again

**Pull request closed without merging**
