### PR TITLE
[#1182] enable user to choose geth instance

### PR DESCRIPTION
**Pull request by tworec**
implements #1882

### CODE REVIEW

**Review by maaktweluit — CHANGES_REQUESTED** [review]
LGTM!

One q on the naming: what does `start_` has to do with the `geth_port`? 
Will approve on reply :)

**Comment by tworec** [comment]
I want to indicate that this port affects locally created geth instance only. This parameter has no meaning if `--start-geth` flag was not provided. It may be even more intuitive to transform `--start-geth` into option with parameter specifying port. What do you think?

**Comment by maaktweluit** [comment]
Thank you for the reply.

Now the naming makes a lot of sense, will approve!

making `--start-geth` smarter sounds like a nice idea but not needed for this fix.

**Review by maaktweluit — APPROVED** [review]

**Comment by maaktweluit** [comment]
rebuild Appveyor now it has an approval.

Please check Shippable, one fix and it will be a green build :)
```
Changed lines findings:

./golem/node.py:147:81: E501 line too long (85 > 80 characters)
```

**Comment by maaktweluit** [comment]
The features in this PR can be added to the GUI in this issue: golemfactory/golem-electron#161

**Comment by tworec** [comment]
closes #1882

**Pull request merged**
