### PR TITLE
lint.sh speedup

### PR DESCRIPTION
**Pull request by tworec**
by checking only changed `.py` files

### CODE REVIEW

**Comment by tworec** [comment]
tihis speeds up my local `lint.sh` from beyond 3mins to under 1 min

```
$ time ./lint.sh 
Using origin/develop as reference branch
Comparing ffad4425...64b83acf
pylint main...      OK
pylint tests...     OK
pycodestyle...      OK
mypy...             OK

real	0m57.968s
user	2m51.648s
sys	0m5.246s
```

**Review by maaktweluit — COMMENTED** [review]
LGTM!

Only thing i can think of is how will it handle added or removed files, this was a problem in the past.
Will approve on reply :)

**Review by badb — APPROVED** [review]

**Comment by tworec** [comment]
thanks @maaktweluit for sneaky and good point. I've checked all combinations I can imagine: deleted file, moved file and added file with some mix thereof. All gone smooth. 

thanks @badb for approoving

I've made some refactoring btw.

**Review by maaktweluit — APPROVED** [review]
LGTM!

Nice refactoring :)

**Comment by tworec** [comment]
thx! ;)
I'm an old bash lover

**Comment by jiivan** [comment]
@tworec Could you confirm wether failed Shippable test is unrelated to your changes?

**Comment by tworec** [comment]
@jiivan It was my fault. Fix on the go

**Review by mfranciszkiewicz — APPROVED** [review]

**Pull request merged**
