### PR TITLE
Remove key_changed methods

### LINKED ISSUE #1413: Remove key_changed methods
Find all occurrences and remove them. One for sure is in `client.py`. We don't want to support this method longer.

### PR DESCRIPTION
**Pull request by ujjwalgulecha**
resolves #1413 
Removing key_changed methods from every file it was present.

### CODE REVIEW

**Comment by ujjwalgulecha** [comment]
Not sure why this failed

**Comment by maaktweluit** [comment]
@ujjwalgulecha circle failed on docker, think a rebuild would solve it there. Appveyor looks good, only needs 1 more approval to also run the slow tests and turn green.

**Comment by ujjwalgulecha** [comment]
@maaktweluit I cannot initiate a re-build as I have no write access. Could you please do that? Thank you!

**Comment by maaktweluit** [comment]
Same here, will ask someone to hit it :)

edit: its building again

**Review by maaktweluit — APPROVED** [review]
LGTM!

Please update to the latest develop ( gui is deleted ) and the next approval can merge

**Comment by ujjwalgulecha** [comment]
@maaktweluit Changes done :)
Only style changes are failing, but its not because of this PR.
Please merge if you think its good!

**Review by badb — APPROVED** [review]
Hi @ujjwalgulecha! Thank you for contributing!
Can you please resolve the p2pservice config? 
Then we will be able to merge it.

**Comment by ujjwalgulecha** [comment]
@badb Done :)

**Comment by ujjwalgulecha** [comment]
@badb @maaktweluit  merge?

**Pull request merged**
