### PR TITLE
Include registry check for vc_redis

### LINKED ISSUE #1468: differences in "Installation-on-Windows" instructions
supposed to be:

55194cdec761dab107ceb5a6

receieved:
 

(modify installer)

after clicking "fix it" (napraw), setup successful 

3c

### PR DESCRIPTION
**Pull request by maaktweluit**
Resolves #1468

### CODE REVIEW

**Comment by maaktweluit** [comment]
Needs testing with different versions of vc_redistributable ( 2015 and 2017 )

Can not be merged before b0.12.0 is merged and this is rebased to reduce conflicts

**Comment by maaktweluit** [comment]
https://buildbot.golem.network/buildbot/#/buildrequests/13604?redirect_to_build=true

**Comment by maaktweluit** [comment]
Build a latest greatest package here:

https://buildbot.golem.network/buildbot/#/builders/1/builds/1348

This can now be tested on:
- Clean windows ( should install vc_redis )
- Windows with Golem 0.15.0 ( should not install vc_redis )
- Clean windows with [vc_redis 2012](https://www.microsoft.com/en-us/download/details.aspx?id=30679) . ( should install vc_redis )
- Clean windows with [vc_redis 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)( should not install vc_redis )
- Clean windows with [vc_redis 2017](https://aka.ms/vs/15/release/VC_redist.x64.exe) ( should not? install vc_redis )

**Comment by ederenn** [comment]
checked all cases. 
Windows with Golem 0.15.0, modal with installation vc question is hidden (probably not installing)
Clean windows with vc_redis 2012, installing newer version
Clean windows with vc_redis 2015, not installing vc
Clean windows with vc_redis 2017, not installing vc

**Review by badb — APPROVED** [review]

**Review by ktomala — APPROVED** [review]
LGTM

**Pull request merged**
