### PR TITLE
Kill docker & try to install vbox driver

### PR DESCRIPTION
**Pull request by badb**

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM

**Comment by maaktweluit** [comment]
@badb can i merge this or would you like one more approval?

**Comment by badb** [comment]
We can:
1) Use only x64 location from @mfranciszkiewicz version
2) Use x64 and remove VM installer (mixed version)
3) Use this version with additional script with killing vm and installing driver script. 

I think that version 2 seems to be the safest and less problematic. @mfranciszkiewicz @maaktweluit what do you think?

**Comment by maaktweluit** [comment]
i think we can go for version 2 for now.
Most people removed all old versions before 0.9
When the new 0.10.0 needs the driver fix we can add it again, but hope we can build it to clean up by itself.

**Comment by mfranciszkiewicz** [comment]
I'm also for option 2.

~BTW, we could upgrade golem's VM just like in [Docker Toolbox installer](https://github.com/docker/toolbox/blob/master/windows/Toolbox.iss#L312).~
Only boot2docker.iso image is updated.

**Comment by badb** [comment]
Version 2 will be implemented in #1683

**Pull request closed without merging**
