### PR TITLE
Wasm verification by redundancy - backported to b0.20.1

### PR DESCRIPTION
**Pull request by kubkon**
This PR is a rebase of #4348 onto `b0.20.1` pre-release branch.

### CODE REVIEW

**Comment by mplebanski** [comment]
Could you point me in any direction with the review?

**Comment by mplebanski** [comment]
Also, have you run those integration tests I created some time ago?

**Comment by kubkon** [comment]
> Could you point me in any direction with the review?

Sure thing. The only *new* things compared to #4348 are the two very last commits. The rest stayed the same.

**Comment by kubkon** [comment]
> Also, have you run those integration tests I created some time ago?

TBH, I'd appreciate some guidance here, as the tests for me were essentially stuck at the waiting phase after the Task was successfully created.

**Comment by kubkon** [comment]
@mplebanski OK, I've now run all VbR integration tests and all pass fine :+1:

**Review by mplebanski — APPROVED** [review]

**Review by shadeofblue — APPROVED** [review]
didnt read lol

**Pull request merged**
