### PR TITLE
Don't try to build Docker images

### PR DESCRIPTION
**Pull request by Krigpl**
Dockerfiles and their context directories will be moved outside Golem repo so attempting to build them won't make sense anymore

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM!

Nice cleanup!

It hurts a bit that the .ini file is using space separated data instead of properties, but that is out of scope to fix here.

**Comment by mfranciszkiewicz** [comment]
LGTM, though I wouldn't merge this yet, unless no one uses Golem to build their Docker images.

**Comment by Krigpl** [comment]
@mfranciszkiewicz And what if they do? This kind of thing won't be supported so what's the reason for delaying?

**Comment by mfranciszkiewicz** [comment]
@Krigpl The reason is that not every image can be uploaded to Docker Hub. E.g. https://github.com/golemfactory/golem/compare/amdgpu?expand=1

**Comment by Krigpl** [comment]
@mfranciszkiewicz Why can't it be uploaded?

**Comment by mfranciszkiewicz** [comment]
Locally installed driver libraries and configuration files need to be added to the image and they must always match what's installed in the host os.

**Comment by Krigpl** [comment]
That sounds like something that should be configured in the runtime rather than built into the Docker image, though. Otherwise images tagged under the same name will be essentially completely different on different hosts which contradicts the idea of consistent Docker images, doesn't it?

**Comment by shadeofblue** [comment]
@Krigpl how did it go? a single repo for everything ? ... and now what?

**Comment by Krigpl** [comment]
@blue Apps were never meant to live inside the same repo

**Pull request closed without merging**
