### PR TITLE
Local geth node cleanup

### PR DESCRIPTION
**Pull request by Krigpl**
`Node` class is now responsible only for creating local Geth process. It wasn't doing much for remote connections anyway.
Connectivity check is done in the SCI module.

### CODE REVIEW

**Comment by mfranciszkiewicz** [comment]
I'm not really convinced that managing remote `geth` nodes should be a part of `EthereumTransactionSystem`. Why is this change required?

**Comment by Krigpl** [comment]
Good point.
I wanted to move all `web3` stuff into `golem_sci`, so this project only uses high level methods like `new_sci_rpc/new_sci_ipc` and doesn't have to create providers and `Web3` objects. It's not strictly required for anything, it was meant to be a simplification. I'll go with a different approach.

**Comment by etam** [comment]
@Krigpl is this PR still relevant? If not, please close it.

**Comment by Krigpl** [comment]
Yeah, I meant to change it to something else but didn't have a chance yet. Will do it another time.

**Pull request closed without merging**
