### PR TITLE
Block multiple restart of a task

### LINKED ISSUE #2285: multiple restart of a task
in Golem version 0.12.0 it is possible to restart the same task multiple times - it should be locked.
Steps to reproduce: click quickly multiple times on restart icon (after timeout of the task).

screen shot 2018-03-01 at 16 07 45 1

### PR DESCRIPTION
**Pull request by jiivan**
fixes: #2285

### CODE REVIEW

**Review by etam — APPROVED** [review]
ok

**Comment by wp31** [comment]
I tried to reproduce this today (version 13.0) and it worked.  (7 identical tasks all of which simultaneously say "Preparing")

**Comment by wp31** [comment]
screen shot 2018-03-20 at 4 07 56 pm

**Comment by etam** [comment]
@wp31 0.13.0 was released a week ago. This fix was merged yesterday into `develop` branch. It'll be present in next release.

**Comment by wp31** [comment]
Ah ok, great thanks @etam!

**Pull request merged**
