### PR TITLE
Test task progress bar #558

### PR DESCRIPTION
**Pull request by banasiakadam60**
Simple progress bar

### CODE REVIEW

**Comment by badb** [comment]
The most irritating and misleading progress bar ever, but probably better then previous empty test  window :) 
Maybe we'll add some serious estimation later, right now it should be sufficient.

**Comment by badb** [comment]
Are you going to change something more here?

**Comment by banasiakadam60** [comment]
Haha, thanks :) As I said last time, for me we shouldn't use this progress bar as an estimator (IMO it can be misleading) and this pr can be closed. But I can try to find some way to show proper progress.

**Comment by badb** [comment]
We may show proper progress when we find out how to measure subtasks progress.

**Comment by banasiakadam60** [comment]
OK, so maybe for now let's merge this PR, and in the mean time I'll try to check the possibilities to show progress

**Pull request merged**
