### PR TITLE
Cleaned up typing for linter errors in taskkeeper

### PR DESCRIPTION
**Pull request by maaktweluit**

### CODE REVIEW

**Comment by jiivan** [comment]
IMHO it looks more like namespace pollution than clean up to me. :)

**Comment by maaktweluit** [comment]
@jiivan that was based on this comment: https://github.com/golemfactory/golem/pull/4120#discussion_r275848258

Will change it according to the solution there then too :)

**Comment by maaktweluit** [comment]
@jiivan updated the PR

IMHO readable code is more important then a clean namespace

**Review by mfranciszkiewicz — APPROVED** [review]
LGTM. 

Improvement suggestion - maybe specify types for the nested collections?

**Review by jiivan — APPROVED** [review]
Readibility is subjective :)

**Comment by maaktweluit** [comment]
@mfranciszkiewicz good one! did not see the typeception, will add those 2

**Pull request merged**
