### PR TITLE
remove eth account from golemcli settings show

### LINKED ISSUE #3024: remove "eth account" in settings show

### PR DESCRIPTION
**Pull request by dybi**
resolves: #3024

### CODE REVIEW

**Review by Krigpl — COMMENTED** [review]
`eth_account` should be also removed from `golem/appconfig.py`

And I know it's not related to the main task but I grepped for `eth_account` and the one from `golem/task/taskstate.py` can be removed as well

**Comment by dybi** [comment]
@Krigpl, done

**Review by Krigpl — APPROVED** [review]
Thanks.
There still some artifacts in `tests/golem/task/test_taskmanager.py`, otherwise it's good.

**Comment by Krigpl** [comment]
Is there anything that stops it from being merged?

**Pull request merged**
