### PR TITLE
Run tasks in Docker containers without root privileges

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
Unlike `su` and running Docker containers as a specified user, both the _effective_ `UID` and `GID` are identical to Golem's user `UID` and `GID` (Linux).

Other changes:
- updated runner scripts
- bumped image versions

### CODE REVIEW

**Comment by badb** [comment]
I get on windows:

> no such file or directory
> Error response from daemon: Container command not found or does not exist. 

It may be a problem with working directory: https://github.com/docker/compose/issues/2950 
Do you have some ideas or should I investigate further on my machine?

**Comment by mfranciszkiewicz** [comment]
Thanks, I'll sort it out.

**Comment by paulperegud** [comment]
Gosu README.md was updated only 3 days ago and it mentions using chroot --userspec as an option:

``` bash
$ docker run -it --rm debian:jessie chroot --userspec=nobody / grep ^[GU]id: /proc/self/status
Uid:    65534   65534   65534   65534
Gid:    65534   65534   65534   65534
```

**Comment by paulperegud** [comment]
chroot requires capabilities we drop while starting container. So, instead I've used su-exec

**Pull request merged**
