### PR TITLE
Remove compatibility check based on app version

### PR DESCRIPTION
**Pull request by pawelkisielewicz**
Resolves https://github.com/golemfactory/golem/issues/3025

### CODE REVIEW

**Comment by mfranciszkiewicz** [comment]
Is this change really needed for 0.19?

**Comment by shadeofblue** [comment]
@pawelkisielewicz please change base to `develop` - it wasn't supposed to be included in `0.19`

**Review by shadeofblue — DISMISSED** [review]
update base

**Review by shadeofblue — APPROVED** [review]
thank_you_roadsign

**Pull request merged**
