### PR TITLE
React to cancelled offer

### PR DESCRIPTION
**Pull request by Krigpl**
As per marketplace doc.
Provider should not be banned when sending `OfferCancelled`.
TODO: timestamp validation

I'm not happy with this approach but I spent some time thinking how to do it differently and everything requires significant refactoring. Alternative solutions are welcomed.

### CODE REVIEW

**Comment by Wiezzel** [comment]
@Krigpl Could you explain why `computation_failed` and `on_computation_failed` need to be two separate methods?

**Comment by Krigpl** [comment]
@Wiezzel Before `computation_failed` was overridden in derived classes so if I wanted to add this extra param I would need to add it everywhere. And I think it's not really relevant for derived classes. 
Current approach solves that. But still, I'm happy to find a better one.

**Comment by Wiezzel** [comment]
@Krigpl OK, sounds reasonable. I can't think of any better solution. Maybe just make `on_computation_failed` a protected method to make clear that it's supposed to be called from `computation_failed` only.

**Comment by Krigpl** [comment]
After offline discussion with @lukasz-glen OfferCancelled shouldn't be treated any differently than other reasons, so these changes are not required.

**Pull request closed without merging**
