### PR TITLE
Fix some of the warnings from CGI/transcoding/master branch

### PR DESCRIPTION
**Pull request by cameel**
This pull request contains lots of small fixes for warnings that `lint.sh` finds on the `CGI/transcoding/master` branch. The fixes come from my other branches and I extracted them here because they're completely independent.

Only some of the warnings are fixed - those from files we actually modified. Others were left unchanged (there are too many of them and they are not the focus of my task).

When reviewing I recommend looking at the commits individually - each one usually fixes one type of warning and the description says what the problem was.

**Note**: my linter fixes changes merged into `develop` in #4092 are not in `CGI/transcoding/master` yet so to see the warnings you'll have to temporarily cherry-pick those commits into your branch and discard them afterwards:
``` bash
git cherry-pick 720d385058425a024fc18721163dffc277724b12..9ab6b5d8ac77d46dd60e336c97d7e95038d2d984
```

### CODE REVIEW

**Comment by cameel** [comment]
`develop` has been recently merged into `CGI/transcoding/master` so I have rebased the code in this pull request and resolved conflicts. I see that many warnings have been fixed in `CGI/transcoding/master` but my changes are still relevant. There were still many unfixed `mypy` and `pylint` warnings. See diffs below.

By the way, note that `lintdiff.sh` is broken on `CGI/transcoding/master` again. This time it hides pylint warnings because pylint crashes while trying to parse `golem/task/server/resources.py`. `lintdiff.sh` treats it as no warnings and says the branch is clean even though it clearly isn't - see the diff.

### pylint warning diff
``` diff
4,31d3
< ************* Module apps.transcoding.ffmpeg.task
< W: apps/transcoding/ffmpeg/task.py:80:4: Useless super delegation in method '__init__' (useless-super-delegation)
< ************* Module apps.transcoding.common
< W: apps/transcoding/common.py:23:19: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< ************* Module apps.transcoding.ffmpeg.utils
< R: apps/transcoding/ffmpeg/utils.py:36:4: Too many local variables (18/15) (too-many-locals)
< W: apps/transcoding/ffmpeg/utils.py:50:21: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/ffmpeg/utils.py:61:21: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< R: apps/transcoding/ffmpeg/utils.py:65:15: Comparison to literal (literal-comparison)
< W: apps/transcoding/ffmpeg/utils.py:70:24: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/ffmpeg/utils.py:89:23: Redefining built-in 'dir' (redefined-builtin)
< W: apps/transcoding/ffmpeg/utils.py:123:21: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< ************* Module apps.transcoding.task
< W: apps/transcoding/task.py:11:0: Reimport 'apps.transcoding.common' (imported line 10) (reimported)
< R: apps/transcoding/task.py:56:0: Too many instance attributes (10/7) (too-many-instance-attributes)
< W: apps/transcoding/task.py:89:27: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:109:24: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:121:20: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:134:20: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:140:21: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< R: apps/transcoding/task.py:146:8: Unnecessary "else" after "return" (no-else-return)
< W: apps/transcoding/task.py:147:25: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:207:30: Redefining built-in 'dict' (redefined-builtin)
< W: apps/transcoding/task.py:206:4: Parameters differ from overridden 'build_full_definition' method (arguments-differ)
< W: apps/transcoding/task.py:240:12: Use % formatting in logging functions and pass the % parameters as arguments (logging-format-interpolation)
< W: apps/transcoding/task.py:262:33: Redefining built-in 'dict' (redefined-builtin)
< W: apps/transcoding/task.py:261:4: Parameters differ from overridden 'build_minimal_definition' method (arguments-differ)
< W: apps/transcoding/task.py:282:33: Redefining built-in 'dict' (redefined-builtin)
```

### mypy warning diff
``` diff
2,21c2
< apps/transcoding/ffmpeg/task.py:46: error: Incompatible types in assignment (expression has type "str", variable has type "Path")
< apps/transcoding/ffmpeg/task.py:92: error: Incompatible types in assignment (expression has type "Type[ffmpegTask]", base class "CoreTaskBuilder" defined the type as "Type[CoreTask]")
< apps/transcoding/ffmpeg/utils.py:136: error: Incompatible default for argument "env" (default has type "None", argument has type "Environment")
< apps/transcoding/task.py:167: error: Incompatible types in assignment (expression has type "Optional[str]", target has type "float")
< apps/transcoding/task.py:168: error: Incompatible types in assignment (expression has type "str", target has type "float")
< apps/transcoding/task.py:171: error: Incompatible types in assignment (expression has type "SubtaskStatus", target has type "float")
< apps/transcoding/task.py:200: error: Need type annotation for 'SUPPORTED_FILE_TYPES'
< apps/transcoding/task.py:201: error: Need type annotation for 'SUPPORTED_VIDEO_CODECS'
< apps/transcoding/task.py:202: error: Need type annotation for 'SUPPORTED_AUDIO_CODECS'
< apps/transcoding/task.py:203: error: Incompatible types in assignment (expression has type "Type[TranscodingTask]", base class "CoreTaskBuilder" defined the type as "Type[CoreTask]")
< apps/transcoding/task.py:218: error: Argument 1 to "AudioParams" has incompatible type "Optional[AudioCodec]"; expected "AudioCodec"
< apps/transcoding/task.py:222: error: Argument 1 to "VideoParams" has incompatible type "Optional[VideoCodec]"; expected "VideoCodec"
< apps/transcoding/task.py:28: error: Incompatible default for argument "bitrate" (default has type "None", argument has type "str")
< apps/transcoding/task.py:28: error: Incompatible default for argument "codec" (default has type "None", argument has type "AudioCodec")
< apps/transcoding/task.py:33: error: Incompatible default for argument "bitrate" (default has type "None", argument has type "str")
< apps/transcoding/task.py:33: error: Incompatible default for argument "codec" (default has type "None", argument has type "VideoCodec")
< apps/transcoding/task.py:33: error: Incompatible default for argument "frame_rate" (default has type "None", argument has type "int")
< apps/transcoding/task.py:33: error: Incompatible default for argument "resolution" (default has type "None", argument has type "Tuple[int, int]")
< apps/transcoding/task.py:62: error: Need type annotation for 'chunks'
< apps/transcoding/task.py:63: error: Need type annotation for 'collected_files'
---
> apps/transcoding/ffmpeg/task.py:91: error: Incompatible types in assignment (expression has type "Type[ffmpegTask]", base class "CoreTaskBuilder" defined the type as "Type[CoreTask]")
35d15
< tests/apps/ffmpeg/task/test_fmmpegtranscoding.py:6: error: Name 'os' already defined (by an import)
```

**Comment by cameel** [comment]
I have rebased the branch on the latest `CGI/transcoding/master`. The commits that touched `ffmpeg-scripts/ffmpeg_commands.py` are now in a separate branch in the `ffmpeg-tools` repo (https://github.com/golemfactory/ffmpeg-tools/pull/1).

**Comment by cameel** [comment]
Just like in case of #4130 not all the tests pass but they're broken on the master branch too. This time a different test is broken:
```
tests/golem/docker/test_docker_manager.py:310: in test_pull_images
    assert pulls[0] == expected
E   AssertionError: assert 9 == 8
```
```
tests/golem/docker/test_docker_manager.py:339: in test_build_images
    assert builds[0] == expected
E   AssertionError: assert 9 == 8
```

It's clearly hard-coded to expect 8 docker images but there are 9 now. Perhaps the test has not been updated after `golemfactory/ffmpeg-experimental:0.94` was added.

**Comment by nieznanysprawiciel** [comment]
Note that all tests passed on CI. I don't know where is problem.

**Pull request merged**
